= Iteration 05: {Projektname}

Die fünfte Iteration des Projekts {Projektname} begann am 4. April 2023 und endete am 18. April 2023. Es ist die erste Iteration des Software Engineering Projektes im Modul Software Engineering zwei. Nach der langen Pause Begann das Projekt ungewohnt, denn nicht nur fehlten zwei der ursprünglichen Mitglieder, sondern mussten wir jetzt auch mit geringeren Personenressourcen, die zweite Hälfte des Software Projektes bestehen. Nach einer gründlichen Phase der Analyse und Ausarbeitung während der Inception- und Elaboration-Phasen im vorherigen Semester, sollte es nun ein enentscheidenden Paradigmenwechsel in der Arbeitsweise geben. Statt in theoretischen Abhandlungen zu verharren, können nun endlich die erstrebenswerten Ideen und funktionalen Konzepte in die Praxis umgesetzt werden. Der erste Prototyp aus dem ersten Semester, welcher kaum mehr als hardcodierte Grundfunktionen bot, sollte jetzt zu einer umfangreichen, benutzbaren Anwendung werden. Um dieses Vorhaben erfolgreich zu realisieren, begann das Team gleich an mehreren Stellen unterschiedliche Funktionen und Kompomenten zu programmieren und zu Implementieren. Möglich gemacht wurde dies durch das Prinzip des Dual Programmings, welches verschiedene Programmierteams anhand der Kenntnisse bildet und diesen den geeignetsten Aufgaben zuweist. Durch diese kohärente Vorgehensweise strebt das Team eine effiziente und ergebnisorientierte Projektentwicklung an. Um ein grundlegendes Verständnis für die Arbeit mit Android Studio und der Programmiersprache Kotlin zu erlangen, wurden den Teammitgliedern zunächst einfache "Einarbeitungsaufgaben" zugewiesen. Hierbei wurden einzelne Elemente des Basic Flows aus UC01 aufgeteilt, um ein erstes Gespür für die Anwendungsentwicklung zu entwickeln. Die Auswahl dieses Use Cases erfolgte nicht nur aufgrund seiner hohen Priorität, sondern auch aufgrund seines linearen und eindeutigen Ablaufs.  In der aktuellen Iteration wird zudem der Aufbau und die Integration des Servers in Angriff genommen. Dieser frühe Kontakt mit der Serveranbindung und den damit verbundenen Herausforderungen bietet dem Team einen ausreichenden Spielraum, um den Server sowie seine funktionalen Anforderungen erfolgreich in die Anwendung einzubinden.

Durch diese strukturierte und zielgerichtete Vorgehensweise im Rahmen des Open Unified Process kann das Projektteam zuversichtlich auf eine erfolgreiche Entwicklung der Anwendung blicken, wobei sowohl die individuellen Kompetenzen als auch die Projektziele optimal berücksichtigt werden.