= Iteration 10 (13.06.-29.06.) {project-name} [LL]
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]

In der 10. Iteration lag der Fokus hauptsächlich auf die Fertigstellung des Projektberichts, vor allem dessen Dokumentation. Der 2. Schwerpunkt lag auf der Vorbereitung des Deployements und der Übergabe des Projekts.

=== 2.7.1. Deployement
Am 29.06. wird die Kundenabnahme statt finden, deren Vorbereitung wir in dieser Iteration geplant haben. Die Kundenabnahme wird in der HTWD statt finden.
Die erstellte Vorlage des Abnahmeprotokolls wird in dem Deployement Meeting abgearbeitet, das heißt die entsprechenden Funktionalitäten und Anforderungen werden von den anwesenden Teammitgliedern vorgestellt und durch den Auftraggeber im besten Fall abgenommen.

=== 2.7.2. Dokumentation
In Rahmen der Dokumentation wurde die Benutzeranleitung und die Betriebsanleitung von Michael Novak, Jonas Pfeiffer ausgearbeitet.
Die Anforderungsspezifikation und Entwicklerdokumentation wurden von Leon Lowa ausgearbeitet. Jedes Teammitglied hat sich freiwillig gemeldet mind. einen Iterationsplan zu ergänzen und die Punkte, die noch notizartig sind auszuformulieren, was den Managment ein bisschen Last abnehmen konnte. Um die Präsentation, Lizensauswahl, Softwaresystem ausarbeiten?? wurden von Magnus Andreas Böhne und Manuel Scheer übernommen. Jedes Teammitglied hat am Enden noch eine reflexion geschrieben.

=== 2.7.3. Implementierung
Mit dieser Iteration trat ein Implementierungsstopp in Kraft. Aufgrund dessen wurden keine neuen Funktionen in das System implementiert und der komplette Fokus wurde so auf den Abschluss des Projekts gelenkt. Es wurden nur noch ganz vereinzelt letzte Bugs gefixed.

=== 2.7.4. Produktpräsentation
Am 26.06. stellten Magnus Böhne und Manuel Scheer unser Projekt, in Form einer Präsentation, vor. Teilnehmer der Präsentation waren die Vortragenden, Kommilitonen und Herr Prof. Anke sowie Herr Zirkelbach. Vorgestellt wurde die Software, zukünftig mögliche Erweiterungen, und die Kerngedanken des Projekts. Am Ende hatten die Teilnehmener noch die Möglichkeit Fragen zu stellen.

=== 2.7.5. Aufgetretene Probleme
Im letzten Kundenmeeting teilte uns Herr Prof. Dr. Iwe mit, dass der Gesetzgeber eine neue Spalte
"e-ID" im Flugbuch fordert. Außerdem äußerte der Themensteller den Wunsch, Piloten aus 
Tabellen importieren zu können. Leider war die Umsetzung der beiden Änderungswünsche für uns
nicht mehr möglich, da wir uns bereits im Implementierungsstopp befanden und es zeitlich nicht
mehr ausreichte neue Funktionen zu implementieren. Wir einigten uns mit dem Themensteller
beide Änderungswünsche als Click-Dummy zu implementieren.

=== 2.7.6. Weitere Fortschritte


=== 2.7.7. Essence-Navigator
Abbildung 13. Aktueller Stand im Essence-Diagramm

