@startuml example-usecase-diagram
left to right direction

' skin parameters for usecase with special stereotype
skinparam usecase<<unspezifiziert>> {
  BackgroundColor #B4EEB4
  BorderColor 		#698b69
  StereotypeFontColor #black
  StereotypeFontSize 10
}


actor Nutzer
actor Roboter

rectangle "Follow-me" {
  usecase "UC01\nRoboter anlegen" as uc01 #B4EEB4;line:698b69
  usecase "UC02\nRoboter bearbeiten" as uc02 #B4EEB4;line:698b69
  usecase "UC03\nRoboter löschen" as uc03 #B4EEB4;line:698b69
  usecase "UC04\nFollow-me Funktion starten" as uc04 #B4EEB4;line:698b69
   usecase "UC05\nFollow-me Funktion ausführen" as uc05 #B4EEB4;line:698b69
  usecase "UC06\nFollow-me Funktion beenden"  as uc06 #B4EEB4;line:698b69
  usecase "UC07\nRoute speichern" as uc07 #B4EEB4;line:698b69
  usecase "UC08\nRoute bearbeiten"  as uc08 #B4EEB4;line:698b69
  usecase "UC09\nRoute löschen" as uc09 #B4EEB4;line:698b69
  usecase "UC10\nRoute ablaufen"  as uc10 #B4EEB4;line:698b69
  usecase "UC11\nRoboter warten"  as uc11 #B4EEB4;line:698b69



  ' single line:
  'usecase "UC05\nAnmeldedaten erfassen" as uc05
  ' multiple lines:

}

Nutzer -- uc01
Nutzer -- uc02
Nutzer -- uc03
Nutzer -- uc04
Nutzer -- uc05
Nutzer -- uc06
Nutzer -- uc07
Nutzer -- uc08
Nutzer -- uc09
Nutzer -- uc10
Nutzer -- uc11
uc04 -- Roboter
uc05 -- Roboter
uc06 -- Roboter
uc10 -- Roboter
uc09 -- Roboter 
@enduml