= System-Wide Requirements: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt <Thema> spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie
* zusätzliche Anforderungen (+) für technische, rechtliche, organisatorische Randbedingungen

NOTE: Die funktionalen Anforderungen, die sich aus der Interaktion von Nutzern mit dem System ergeben, sind als Use Cases in einem separaten Dokument festgehalten. [hier ggf. Verweis einfügen]


== Systemweite funktionale Anforderungen

SWFA-1: ::
* Die GPS-Tracks müssen dauerhaft gespeichert und bei Bedarf aktualisiert sein.
Wenn ein aufgenommenener GPS-Track hochgeladen wird, ist dieser dann dauerhaft verfügbar.
SWFA-2: ::
* Während der Nutzung der App muss dauerhaft eine Internetverbindung bzw. Verbindung zum Server bestehen.
Wenn man die App ohne Internetzugang nutzen möchte, bekommt man einen sofortigen Hinweis darauf die Verbindung herzustellen.
SWFA-3: ::
* Bei Nichtbestehen einer GPS Verbindung soll der Roboter stehen bleiben. 
Sollte während einer Aktion keine GPS Verbindung mehr bestehen, soll der Roboter seine Aktion abbrechen und nicht fortführen.


//Angabe von system-weiten funktionalen Anforderungen, die nicht als Use Cases ausgedrückt werden können. Beispiele sind Drucken, Berichte, Authentifizierung, Änderungsverfolgung (Auditing), zeitgesteuerte Aktivitäten (Scheduling), Sicherheit / Maßnahmen zum Datenschutz


== Qualitätsanforderungen für das Gesamtsystem
//Qualitätsanforderungen repräsentieren das "URPS" im FURPS+ zu Klassifikation von Anforderungen

=== Benutzbarkeit (Usability)

NFAU-1: ::
* Auf Anglizismen sowie technische und informatische Fachbegriffe soll verzichtet werden. Die Anwendung wird einer fachfremden Person zur Überprüfung auf Verständlichkeit vorgeführt.

NFAU-2: ::
* Die Anwendung soll ohne technische Kenntnisse des Nutzers bedienbar sein. Die Anwendung wird einer fachfremden Person zur Überprüfung auf Verständlichkeit vorgeführt.

NFAU-3: ::
* Zur Minimierung der Interaktionsauswahl, der Konfusion und zur Steigerung der Übersichtlichkeit werden Auswahlmöglichkeiten durch Ausgrauen reduziert, wenn sie zum Zeitpunkt der Auswahl technisch oder anderweitig nicht verfügbar sind. Zur Überprüfung werden die minimal verfügbaren Auswahlmöglichkeiten real mit denen in der Anwendung verglichen.

NFAU-4: ::
* Zur Nutzung der Kernfunktionalität soll die Anwendung mit minimaler Klickzahl steuerbar sein. Dafür werden diese auf der Startseite auswählbar sein. Zur Überprüfung soll die Kernfunktionalität mit weniger als fünf Klicks erfüllbar sein.

NFAU-5: ::
* Fehler werden dem Nutzer offensichtlich, schnell und verständlich angezeigt. Dafür werden ihm Pop-Ups zur Bestätigung angezeigt. Zur Überprüfung wird ein Fehler simuliert und einem Fachfremden Nutzer vorgeführt.




//Beschreiben Sie Anforderungen für Eigenschaften wie einfache Bedienung, einfaches Erlernen, Standards für die Benutzerfreundlichkeit, Lokalisierung (landesspezifische Anpassungen von Sprache, Datumsformaten, Währungen usw.)

=== Zuverlässigkeit (Reliability)

NFAR-1: :: 
* Bei instabiler Verbindung zum Server sollen nur vollständig und korrekt gesendete Befehle/Operationen ausgeführt werden.
Zur Überprüfung wird getestet, ob die empfangenen Daten konsistent und nicht lückenhaft sind. 

NFAR-2: ::
* Nur Roboter der eigenen Flotte sollen genutzt werden können.
Zur Überprüfung sollen ein Key angelegt werden, um den Roboter nutzen zu können.

// Zuverlässigkeit beinhaltet die Fähigkeit des Produkts und/oder des Systems unter Stress und ungünstigen Bedingungen am laufen zu bleiben. Spezifizieren Sie Anforderungen für zuverlässige Akzeptanzstufen, und wie diese gemessen und evaluiert werden. Vorgeschlagene Themen sind Verfügbarkeit, Häufigkeit und Schwere von Fehlern und Wiederherstellbarkeit.

=== Effizienz (Performance)

NFAP-1: ::
* Die App soll ein Wechsel von Seite zu Seite und die Benutzung bestimmter Aktionen innerhalb der App in maximal 3 Sekunden* ermöglichen.
Zur Überprüfung werden manuelle bzw. automatische Tests feststellen, ob alle Anforderungen innerhalb der gegebenen Zeit unter optimalen Bedingungen ablaufen.

NFAP-2: ::
* Gewählte Aktionenen der App sollen innerhalb von 1000 Millisekunden* an den Server gesendet, verarbeitet und verifiziert werden.
Zur Überprüfung werden manuelle bzw. automatische Tests feststellen, ob alle Anforderungen innerhalb der gegebenen Zeit ablaufen.

NFAP-3: ::
* Die Speicherung der Daten soll nicht länger als 5 Sekunden dauern.
Zur Überprüfung werden manuelle bzw. automatische Tests feststellen, ob alle Anforderungen innerhalb der gegebenen Zeit ablaufen.

NFAP-4: ::
* Die Routen sollen möglichst gleich absolviert werden.
Zur Überprüfung wird das Intervall der GPS Aufzeichnung möglichst kurz gehalten und automatisch überprüft, ob die aktuellen GPS Daten mit denen der Route übereinstimmen

NFAP-5: ::
* Gesendete Kommandos an den Roboter sollen spätestens 6 Sekunden* nach Auswahl ausgeführt werden.
Zur Überprüfung werden manuelle bzw. automatische Tests feststellen, ob alle Anforderungen innerhalb der gegebenen Zeit ablaufen.

*ausgegangen wird dabei von angemessenen Hardwarekomponenten und einer stabilen Internetverbindung

// Die Performanz Charakteristiken des Systems sollten in diesem Bereich ausgeführt werden. Beispiele sind Antwortzeit, Durchsatz, Kapazität und Zeiten zum Starten oder Beenden.

=== Wartbarkeit (Supportability)

NFAS-1: ::
* Die App soll entwicklungsrelevante Systemfehler loggen können und an die Entwickler weiterleiten.
Zur Überprüfung wird ein solcher Fehler simuliert und kontrolliert, ob die Entwickler über diesen Informiert wurden.

NFAS-2: ::
* Die App soll zu jederzeit einfach erweiterbar sein, damit fehlende Funktionen hinzugefügt und auftretende Fehler beseitigt werden können.
Zur Weiterentwicklung soll die Ausarbeitung eine Basis darstellen, damit die App zum späteren Zeitpunkt universell für unterschiedliche Roboter einsetzbar ist.


// Dieser Bereich beschreibt sämtliche Anforderungen welche die Supportfähigkeit oder Wartbarkeit des zu entwickelnden Systems verbessern, einschließlich Anpassungsfähigkeit und Erweiterbarkeit, Kompatibilität, Skalierbarkeit und Anforderungen bezüglich der System Installation sowie Maß an Support und Wartbarkeit.


== Zusätzliche Anforderungen

=== Einschränkungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Ressourcenbegrenzungen
* zu nutzende Komponenten / Bibliotheken / Frameworks
* Vorgaben für die Programmiersprache
* zu unterstützende Plattformen / Betriebssysteme
* Physische Begrenzungen für Hardware, auf der das System betrieben werden soll

=== Organisatorische Randbedingungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Anforderungen an Betrieb, Management und Wartung der Anwendung
* zu beachtende Standards, Normen und Regeln

=== Rechtliche Anforderungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Lizensierung der Anwendung
* Datenschutz
