//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).


//Use Cases erste Überlegnung: Starten des Follow-Me, Verbindung mit Roboter herstellen, About-Button,... 
== Use-Case: Senden des Warte Befehls

=== Kurzbeschreibung
//<Kurze Beschreibung des Use Case>

Dieser Use Case beschreibt das Versenden des Warte Befehls in der Follow-Me-App

=== Kurzbeschreibung der Akteure

==== <Nutzer (User)>
    Der Nutzer ist der Hauptakteur in diesem Use Case, durch Ihn wird das Use Case aufgerufen und gestartet.

==== <Anwendung>
    Die Anwendung dient dem Nutzer als grafische Oberfläche um Aktionen durchzuführen und Entscheidungen zu treffen. Außerdem übermittelt sie im Hintergrund die nötigen Daten an den Server.

==== <Server>
    Der Server empfängt die Daten durch die Anwendung und leitet diese an den jeweiligen Roboter weiter. Er dient als Schnittstelle der Akteure.

==== <Roboter>
    Er empfängt Signale und gibt Rückmeldung über den Erhalt der Signale.


=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

==== <Internetverbindung>
Die untereinander kommunizierenden Akteure (Anwendung, Server, Roboter) benötigen eine stabile Internetverbindung.

==== <Roboter existent>
Es wurden bereits Roboter gespeichert.

==== <Roboter ist aktiv>
Ein Roboter hat momentan einen aktiven Folge oder Zurückkehren Befehl.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")


. Der Use Case beginnt, wenn der Nutzer im Hauptmenü der Anwendung auswählt, dass er einen Roboter warten lassen will.
. Das System zeigt dem Nutzer eine Liste der verfügbaren Roboter an. 
. Der Nutzer wählt einen Roboter aus der zuvor angezeigten Liste aus.
. Das System zeigt dem Nutzer eine Bestätigung an.
. Das Use Case endet wenn der Roboter seinen momentanen Befehl pausiert und an seinem momentanen Standort wartet.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== Keine verfügbaren Roboter

Falls in Schritt 2 kein verfügbarer Roboter gefunden wurde, dann

    . Die Anwendung zeigt dem Nutzer an, dass keine Roboter verfügbar sind, denen der Warte Befehl gegeben werden kann.
    . Das Use Case endet erfolglos, die Anwendung zeigt dem Nutzer das Hauptmenü. 


==== Der Nutzer bricht das Use Case ab

Falls der Nutzer, in einem der Schritte die Zurück Funktion seines Gerätes nutzt, dann

    . Das System fragt den Nutzer, ob er den aktuellen Vorgang beendet will.
    . IF Der Nutzer wählt "Ja" aus.
        .. Das Use Case endet erfolglos, die Anwendung zeigt dem Nutzer das Hauptmenü. 
    . ELSE 
        .. Der Use Case wird in dem Schritt fortgesetzt, in dem der Nutzer die Zurück Funktion betätigt hat.

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern

==== <Der Nutzer will einem Roboter den Warte Befehl geben>

. Die Anwendung fragt eine Liste aller Roboter ab, die zuvor den Folge oder Zurückkehren Befehl erhalten haben vom Server ab.
. Der Server sendet eine Liste aller verfügbaren Roboter an die Anwendung.


==== <Der Nutzer wählt einen Roboter aus der Liste>
. Die Anwendung sendet die Daten des ausgewählten Roboters an den Server.
. Die Anwendung sendet die Daten des Nutzer an den Server.
. Der Server sendet den Befehl an den Roboter.
. Der Roboter bestätigt den Befehl erhalten zu haben an den Server.
. Der Server sendet eine erfolgreiche Bestätigung an die Anwendung.





=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.

==== Der Nutzer bricht das Use Case ab
Der Roboter führt den Folge Befehl nicht aus.


=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.

==== Erfolgreiches Beenden
Der Roboter hat seinen aktuellen Befehl pausiert und wartet nun auf seiner aktuellen Position auf weitere Befehle.

==== Erfolgloses Beenden
Wird das Use Case erfolglos beendet, wird dem Nutzer das Hauptmenü gezeigt, der zuvor ausgewählte Roboter behält seinen aktuellen Zustand bei.

=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.

==== Reliability
Verfügbarkeit: Der Server sollte dauerhaft ansprechbar sein.