//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).


//Use Cases erste Überlegnung: Starten des Follow-me, Verbindung mit Roboter herstellen, About-Button,... 
== Use-Case: Route speichern

=== Kurzbeschreibung
//<Kurze Beschreibung des Use Case>
Dieser Use Case beschreibt das Speichern einer Route nach Beenden der Follow-me Funktion der Follow-me-App.

=== Kurzbeschreibung der Akteure

==== Nutzer (User)

Der Nutzer ist der Hauptakteur in diesem Use Case, durch Ihn wird das Use Case aufgerufen und gestartet.


=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

==== Internetverbindung
Der Nutzer benötigt eine stabile Internetverbindung zum System.


==== Abgeschlossene Aktivität
Damit dieser Use Case beginnen kann, muss das Use Case "Follow-me Funktion beenden" vorausgegangen sein.



=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn das Use Case "Beenden der Follow-me Funktion" endet.
. Die Anwendung fragt den Nutzer, ob dieser die soeben vollendete Route speichern möchte.
. Der Nutzer wählt aus, dass die Route gespeichert werden soll.
. Der Nutzer gibt der Route einen Namen.
. Die Anwendung zeigt dem Nutzer an, dass die Route erfolgreich gespeichert wurde.
. Das Use Case endet, wenn die Anwendung dem Nutzer die Route, den Zeitpunkt der Speicherung sowie den Routennamen anzeigt.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== Nutzer möchte die soeben vollendete Route nicht speichern.

Falls in Schritt 3 ausgewählt wird, dass die Route nicht abgespeichert werden soll:

    . Die Anwendung zeigt dem Nutzer an, dass die Route nicht gespeichert wird.
    . Das Use Case endet erfolgreich, die Anwendung zeigt dem Nutzer den Startbildschirm an.

==== Speicher des Servers ist vollständig belegt.

Falls in Schritt 4 die Daten nicht gespeichert werden können, da der Server keine weiteren Speichermöglichkeiten zur Verfügung hat.

    . Der Server sendet der Anwendung, dass die Daten nicht gespeichert werden konnten.
    . Die Anwendung zeigt dem Nutzer, dass die Daten nicht gespeichert werden konnten, da der Speicher des Servers vollständig belegt wurde.
    . WHILE Nicht genügend Speicherplatz zur Verfügung um Route zu speichern
    .. Die Anwendung zeigt dem Nutzer, wieviel Speicherplatz noch benötigt wird, um die Route erfolgreich speichern zu können.
    .. Die Anwendung fragt den Nutzer, ob er bereits gespeicherte Routen löschen möchte um Speicher des Servers freizugeben.
    .. IF Nutzer wählt aus, eine bereits gespeicherte Route zu löschen.
    ... Die Anwendung zeigt dem Nutzer eine Liste aller gespeicherten Routen sowie den jeweiligen Speicherbedarf einer Route.
    ... Der Nutzer wählt die zu löschende Route aus.
    .. ELSE 
    ... Die Anwendung zeigt dem Nutzer, dass die Route aufgrund von unzureichendem Speicher nicht gespeichert werden konnte.
    ... Das Use Case endet erfolglos, die Route wird nicht abgespeichert.
    . Das Use Case wird bei Schritt 4 fortgesetzt.



==== Reservierter Speicher für den Nutzer ist vollständig belegt.

Falls in Schritt 4 die Daten nicht gespeichert werden können, da der reservierte Speicher für den Nutzer vollständig belegt ist.

    . Der Server sendet der Anwendung, dass die Daten nicht gespeichert werden konnten.
    . Die Anwendung zeigt dem Nutzer, dass die Daten nicht gespeichert werden konnten, da der reservierte Speicher des Nutzers vollständig belegt wurde.

    . WHILE Nicht genügend Speicherplatz zur Verfügung um Route zu speichern
    .. Die Anwendung zeigt dem Nutzer, wieviel Speicherplatz noch benötigt wird, um die Route erfolgreich speichern zu können.
    .. Die Anwendung fragt den Nutzer, ob er bereits gespeicherte Routen löschen möchte um Speicher des Servers freizugeben.
    .. IF Nutzer wählt aus, eine bereits gespeicherte Route zu löschen.
    ... Die Anwendung zeigt dem Nutzer eine Liste aller gespeicherten Routen sowie den jeweiligen Speicherbedarf einer Route.
    ... Der Nutzer wählt die zu löschende Route aus.
    .. ELSE 
    ... Die Anwendung zeigt dem Nutzer, dass die Route aufgrund von unzureichendem Speicher nicht gespeichert werden konnte.
    ... Das Use Case endet erfolglos, die Route wird nicht abgespeichert.
    . Das Use Case wird bei Schritt 4 fortgesetzt.


==== Daten konnten nicht vollständig übermittelt werden.

Falls in Schritt 3 die Daten nicht erfolgreich übermittelt werden konnten.

        . WHILE Keine Antwort vom Server
        .. Die Anwendung teilt dem Nutzer mit, dass die Daten nicht übermittelt werden konnten.
        .. Die Anwendung teilt dem Nutzer mit, dass er seine Verbindung überprüfen soll.
        .. Die Anwendung fragt den Nutzer, ob er es erneut versuchen möchte.
        .. IF Nutzer möchte erneut versuchen, die Daten an den Server zu übermitteln.
        ... Das Use Case wird bei Schritt 3 fortgesetzt.
        .. ELSE
        ... Das Use Case endet erfolglos, die Route wird nicht abgespeichert.

==== Routenname exisitiert bereits.

Falls in Schritt 4 ermittelt wird, dass eine Route mit der eingegebenen Bezeichnung bereits existiert.

    . WHILE Name exisitert bereits
    .. Die Anwendung zeigt dem Nutzer, dass dieser Name bereits verwendet wird.
    .. Die Anwendung fragt nach einem neuen Routennamen.
    .. Der Nutzer gibt einen neuen Namen ein.
    . Das Use Case wird bei Schritt 5 fortgesetzt.



=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.

Die Route und der zugehörige Nutzer sind gespeichert.
Der Nutzer hat das erfolgreiche abschließen des Speichervorgangs bestätigt bekommen.
Die Logdatei hat Beginn des Use Cases sowie Ende und Beendigungsgrund gespeichert. 
