//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).


//Use Cases erste Überlegnung: Starten des Follow-Me, Verbindung mit Roboter herstellen, About-Button,... 
== Use-Case: Anlegen eines Roboters

=== Kurzbeschreibung
Dieser Use Case beschreibt das Anlegen eines Roboters um diesen in weiteren Use Cases verwenden zu können.


=== Kurzbeschreibung der Akteure

==== Nutzer (User)

    Der Nutzer ist der Hauptakteur in diesem Use Case, durch ihn wird der Use Case aufgerufen und gestartet.


==== Anwendung

    Die Anwendung dient dem Nutzer als grafische Oberfläche, um Aktionen durchzuführen und Entscheidungen zu treffen. Außerdem übermittelt sie im Hintergrund die nötigen Daten an den Server.

==== Server

    Der Server empfängt die Daten durch die Anwendung und leitet diese an den jeweiligen Roboter weiter. Er dient als Schnittstelle der Akteure.

    
==== Roboter

    Er empfängt Signale und gibt Rückmeldung über den Erhalt der Signale.


=== Vorbedingungen

==== <Internetverbindung>
Die untereinander kommunizierenden Akteure (Anwendung, Server, Roboter) benötigen eine stabile Internetverbindung.

==== <Roboter verfügbar>
Es existiert ein Roboter welcher bisher von keinem Nutzer gespeichert wurde.

==== <Roboter Authentifizieren>
Der Nutzer kennt die Hash-Kombination des zu speichernden Roboters.


=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Nutzer in der App die Schaltfläche "Roboter anlegen" betätigt.
. Das System fragt nach einem Token.
. Der Nutzer gibt das passende Token ein.
. Das System findet den Roboter und vergleicht, ob dieses Token sich bereits in der Liste der gespeicherten Roboter befindet.
. Das Token des Roboters befindet sich noch nicht in der Liste, daher speichert das System dieses und fragt den Nutzer nach einem Namen für den Roboter.
. Der Nutzer vergibt einen Namen und bestätigt diesen.
. Das System überprüft, ob der Name bereits vergeben ist.
. Der Name ist noch nicht vergeben, daher speichert das System den neuen Roboter unter dem eingegebenen Namen samt dem Token in der Liste der gespeicherten Roboter.
. Das System bestätigt das erfolgreiche Speichern des Roboters.
. Das Use Case endet, wenn das System dem Nutzer die Daten des angelegten Roboters (Name, Token) anzeigt.


=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== System findet keinen Roboter zu diesem Token
Falls das System in Schritt 4 keinen Roboter findet, dann:


. Das System gibt dem Nutzer eine Fehlermeldung zurück.
. Das System fragt den Nutzer ob er erneut einen Token eingeben will.
. IF Nutzer möchte erneut einen Token eingeben
.. Das Use Case wird bei Schritt 4 fortgesetzt.
. ELSE
.. Das Use Case wird bei Schritt 2 fortgesetzt.

==== Token des Roboters befindet sich bereits in der Liste der gespeicherten Roboter
Falls sich das Token des Roboters in Schritt 5 bereits in der Liste der gespeicherten Roboter befindet, dann

. Das System sagt dem Nutzer, dass sich der Roboter bereits in der Liste befindet.
. Das System fragt den Nutzer, ob er ein anderes Token eingeben möchte oder ob er das Speichern eines Roboters abbrechen möchte.
. IF Nutzer möchte ein anderes Token eingeben
.. Das Use Case wird bei Schritt 4 fortgesetzt
. ELSE
.. Das Use Case endet erfolglos und das System zeigt dem Nutzer das Menü "Roboter verwalten".

==== Name des Roboters ist bereits vergeben
Falls das System feststellt, dass der vom Nutzer eingegebene Name in Schritt 8 bereits vergeben ist, dann

. Das System zeigt dem Nutzer an, dass dieser Name bereits vergeben ist.
. Das System fragt den Nutzer ob er einen neuen Namen vergeben möchte.
. IF Nutzer möchte neuen Namen vergeben
.. Das Use Case wird bei Schritt 8 fortgesetzt.
. ELSE 
.. Das Use Case endet erfolglos, das System zeigt dem Nutzer das Menü "Roboter verwalten".

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern

==== <Unterablauf 1>
. <Unterablauf 1, Schritt 1>
. …
. <Unterablauf 1, Schritt n>

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.


==== Erfolgreicher Ablauf
Der Nutzer X gibt den Token seines Roboters an und bestätigt diesen. Er wird nach einem Namen für den Roboter gefragt und nennt diesen "Roboter 1". Der Nutzer bestätigt seine Eingaben und bekommt die Daten seines eben angelegten Roboters angezeigt. Der Roboter ist erfolgreich angelegt.


=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.


Der Roboter ist eindeutig identifizierbar eingespeichert.
Der Nutzer hat das erfolgreiche Abschließen des Speichervorgangs bestätigt bekommen.
Die Logdatei hat Beginn des Use Cases sowie Ende und Beendigungsgrund gespeichert. 


=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.

==== Funktionalität
Authentifizierung: Der Roboter und der Nutzer müssen eindeutig über Token und (IP, Mac-Adresse) authentifiziert werden um einen fehlerfreien Ablauf im weiteren Nutzen des Systems gewährleisten zu können.
