//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).


//Use Cases erste Überlegnung: Starten des Follow-me, Verbindung mit Roboter herstellen, About-Button,... 
== Use-Case: Ablaufen einer Route

=== Kurzbeschreibung
//<Kurze Beschreibung des Use Case>
Dieser Use Case beschreibt das Starten der "Route ablaufen" Funktion. In diesem Use Case wird ausschließlich die Seite des Nutzers betrachtet. Der Roboter gibt einzig Signale darüber, ob er alle Befehle erhalten hat.


=== Kurzbeschreibung der Akteure

==== Nutzer (User)
Durch den Nutzer wird das Use Case aufgerufen und gestartet.


==== Roboter
Der Roboter soll eine ausgewählte Route, nach Erhalt des Befehls, selbstständig ablaufen. 

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

==== Internetverbindung
Die untereinander kommunizierenden Akteure (Nutzer, Roboter) benötigen eine stabile Internetverbindung zum System.

==== Roboter existent
Es wurden bereits Roboter gespeichert.

==== Roboter verfügbar
Ein Roboter ist verfügbar (führt keine anderen Aktionen aus).

==== Routen verfügbar
Es befinden sich bereits Routen in der Liste der gespeicherten Routen.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Nutzer in der App eine Route aus der Liste der Routen auswählt.
. Das System zeigt dem Nutzer alle zu der ausgewählten Route verfügbaren Daten an (Name, Token etc.)
. Der Nutzer betätigt die Schaltfläche "Route ablaufen".
. Das System zeigt dem Nutzer eine Liste aller verfügbaren Roboter an.
. Der Nutzer wählt einen Roboter aus der Liste der verfügbaren Roboter aus.
. Das System fragt den Nutzer erneut, ob der ausgewählte Roboter die ausgewählte Route ablaufen soll.
. Der Nutzer bestätigt. 
. Das System übermittelt die Anweisung an den Roboter.
. Der Roboter bestätigt Erhalt der Anweisung.
. Das System bestätigt das erfolgreiche Starten der Funktion.
. Das Use Case endet erfolgreich, dem Nutzer wird erneut die Liste der Routen angezeigt.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf


=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.


Der Nutzer hat das Erfolgreiche Starten der Funktion bestätigt bekommen.
Der Roboter beginnt die Route abzulaufen.
Die Logdatei hat Beginn des Use Cases sowie Ende und Beendigungsgrund gespeichert. 


=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.

=== Usability 
Erlernbarkeit: Das Starten der "Ablaufen einer Route" Funktion soll intuitiv und linear funktionieren.
