//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).


//Use Cases erste Überlegnung: Starten des Follow-me, Verbindung mit Roboter herstellen, About-Button,... 
== Use-Case: Follow-me Funktion ausführen

=== Kurzbeschreibung
Dieser Use Case beschreibt den Ablauf zwischen dem Use Case "Follow-me Funktion starten" und "Follow-me Funktion beenden".

=== Kurzbeschreibung der Akteure

==== Nutzer (User)
Der Nutzer ist der Hauptakteur in diesem Use Case, durch ihn wird das Use Case aufgerufen und gestartet.

==== Roboter
Er empfängt Signale und gibt Rückmeldung über den Erhalt der Signale.

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

==== Internetverbindung
Die untereinander kommunizierenden Akteure (Nutzer, Roboter) benötigen eine stabile Internetverbindung zum System.

==== GPS Verbindung
Der Nutzer und der ausgewählte Roboter benötigen eine stabile GPS Verbindung.

==== Roboter existent
Es wurden bereits Roboter gespeichert.

==== Roboter verfügbar
Ein Roboter ist verfügbar (führt keine anderen Aktionen aus).



=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn das Use Case "Follow-me Funktion starten" endet.
. Das System zeigt dem Nutzer einen Bildschirm mit seinem Standort, dem Standort des Roboters sowie der Zeit die seit Beginn des Use Cases vergangen ist.
. WHILE Nutzer bewegt sich
.. Das System sendet die GPS Daten des Nutzers an den Roboter.
.. Der Roboter bestätigt das Erhalten der GPS Daten.
.. Der Roboter bewegt sich zu den erhaltenen GPS Daten.
.. Der Roboter sendet seine GPS Daten an das System.
.. Das System aktualisiert die Positionsänderungen auf dem Bildschirm.
. Das Use Case endet, wenn die Schaltfläche "Follow-me Beenden" betätigt wird.


=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== Entfernung zwischen Roboter und Nutzer zu groß
Falls das System in Schritt 3 d bemerkt, dass die Distanz zwischen Nutzer und Roboter größer als 5 Meter ist

. WHILE Distanz zwischen Roboter und Nutzer größer als 5 Meter
.. Das System zeigt dem Nutzer eine Fehlermeldung.
.. Das System macht den Nutzer auf die Fehlermeldung bemerkbar (Gerät spielt Ton ab, Gerät vibriert).
.. Das System sendet die GPS Daten des Nutzers an den Roboter.
.. Der Roboter bestätigt das Erhalten der GPS Daten.
.. Der Roboter bewegt sich zu den erhaltenen GPS Daten.
.. Der Roboter sendet seine GPS Daten an das System.
. Das Use Case wird bei Schritt 3 e fortgesetzt.


=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.

==== Erfolgreiches Ausführen der Follow-me Funktion
Der Nutzer hat das Use Case "Follow-me Funktion starten" beendet und in diesem Roboter 2 ausgewählt. Der Nutzer sieht einen Bildschirm mit seinem Standort, dem Standort von Roboter 2 und der vergangenen Zeit seit Beginn des Use Cases. Der Nutzer bewegt sich 5 Meter nach Norden, nach kurzer Zeit wird ihm seine Positionsänderung auch auf dem Bildschirm angezeigt. Der Roboter folgt dem Nutzer, bis sich auch sein Standort mit dem des Nutzers wieder gleicht. Der Nutzer sieht, dass beide Positionen wieder übereinstimmen und geht dementsprechend weiter in die gewünschte Richtung. Er wiederholt dies bis er sein Ziel erreicht. Wenn das Ziel erreicht ist, wählt der Nutzer "Follow-Me beenden" und beendet damit das Use Case. Für ihn beginnt nun automatisch das Use Case "Follow-me Funktion beenden".


=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.

Use Case "Follow-me Funktion beenden" hat begonnen.
Die Logdatei hat Beginn des Use Cases sowie Ende und Beendigungsgrund gespeichert. 

=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.

==== Usability 
Erlernbarkeit: Das Ausführen der Follow-me Funktion ist eine grundlegende Funktion des Systems und soll intuitiv und linear funktionieren.
