//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).


//Use Cases erste Überlegnung: Starten des Follow-me, Verbindung mit Roboter herstellen, About-Button,... 
== Use-Case: Roboter löschen

=== Kurzbeschreibung
Dieser Use Case beschreibt das Löschen eines Roboters, um ihn beispielsweise neu einzuspeichern oder das System zu bereinigen.

=== Kurzbeschreibung der Akteure

==== Nutzer (User)

Der Nutzer ist der Hauptakteur in diesem Use Case, durch ihn wird das Use Case aufgerufen und gestartet.

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

==== Internetverbindung
Der Nutzer benötigt eine stabile Internetverbindung zum System.

==== Verfügbare Roboter
Es befinden sich bereits Roboter in der Liste der gespeicherten Roboter.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Nutzer in der App einen Roboter aus der Liste der Roboter auswählt.
. Das System zeigt dem Nutzer alle zu dem ausgewählten Roboter verfügbaren Daten an (Name, Token etc.)
. Der Nutzer wählt die Schaltfläche "Roboter löschen" aus.
. Das System fragt den Nutzer, ob der Roboter wirklich gelöscht werden soll.
. Der Nutzer bestätigt, dass er den Roboter löschen möchte.
. Das System löscht den ausgewählten Roboter.
. Das Use Case endet erfolgreich, dem Nutzer wird erneut die Liste der Roboter angezeigt.


=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== Der Nutzer möchte den Roboter nicht löschen
Falls der Nutzer in Schritt 5 den Roboter nicht löschen möchte.

. Der Nutzer bestätigt nicht, dass er den Roboter löschen möchte.
. Das System nimmt keine Änderung vor.
. Das Use Case endet erfolglos, dem Nutzer wird erneut die Liste der Roboter angezeigt.


==== Der ausgewählte Roboter führt eine Aktion aus
Falls der in Schritt 3 ausgewählte Roboter eine Aktion ausführt.

. Das System zeigt dem Nutzer, dass der ausgewählte Roboter im Moment eine Aktion ausführt.
. Das System fragt, ob die Aktion abgebrochen werden soll.
. IF Nutzer wählt aus, dass die Aktion abgebrochen werden soll.
.. Das System bricht die Aktion des Roboters ab.
.. Das Use Case wird bei Schritt 4 fortgesetzt.
. ELSE 
.. Das System zeigt dem Nutzer, dass die Aktion des Roboters nicht abgebrochen wurde.
.. Das Use Case endet erfolglos, dem Nutzer wird erneut die Liste der Roboter angezeigt.



=== Nachbedingungen

Alle dem Roboter zugehörigen Daten sind auf dem Gerät des Nutzers sowie in der Datenbank des Servers gelöscht. Der Roboter befindet sich nicht länger in der Liste der Roboter.
Der Nutzer hat das erfolgreiche Löschen des Roboters bestätigt bekommen.
Die Logdatei hat Beginn des Use Cases sowie Ende und Beendigungsgrund gespeichert. 


