//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).


//Use Cases erste Überlegnung: Starten des Follow-me, Verbindung mit Roboter herstellen, About-Button,... 
== Use-Case: Roboter bearbeiten

=== Kurzbeschreibung
Dieser Use Case beschreibt das Bearbeiten eines Roboters um zum Beispiel den Namen anzupassen.

=== Kurzbeschreibung der Akteure

==== Nutzer (User)

Der Nutzer ist der Hauptakteur in diesem Use Case, durch ihn wird das Use Case aufgerufen und gestartet.


=== Vorbedingungen

==== Internetverbindung
Der Nutzer benötigt eine stabile Internetverbindung zum System.

==== Verfügbare Roboter
Es befinden sich bereits Roboter in der Liste der gespeicherten Roboter.


=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Nutzer in der App einen Roboter aus der Liste der Roboter auswählt.
. Das System zeigt dem Nutzer alle zu dem ausgewählten Roboter verfügbaren Daten an (Name, Token etc.)
. WHILE Nutzer möchte Änderung der Daten vornehmen.
.. Der Nutzer drückt auf die Daten, die zu ändern sind. 
.. Der Nutzer ändert die Daten.
. Der Nutzer wählt die Schaltfläche "Änderungen Speichern".
. Das System zeigt dem Nutzer alle Daten die geändert werden.
. Der Nutzer bestätigt erneut, dass er die Daten ändern möchte.
. Das System ändert die Daten des ausgewählten Roboters.
. Das System zeigt dem Nutzer die geänderten Daten an.
. Das Use Case endet erfolgreich, dem Nutzer wird erneut die Liste der Roboter angezeigt.


=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== Der Nutzer möchte die Änderungen nicht übernehmen
Falls der Nutzer in Schritt 6 die Änderungen nicht übernehmen möchte

. Der Nutzer bestätigt nicht, dass er die Daten ändern möchte.
. Das System verwirft die Änderungen.
. Das Use Case endet erfolglos, dem Nutzer wird erneut die Liste der Roboter angezeigt.


==== Geänderte Daten sind bereits an einen anderen Roboter vergeben
Falls der Nutzer in Schritt 4 Daten so geändert hat, dass diese sich mit den Daten anderer Roboter überschneiden (zum Beispiel: Name)

. Das System zeigt dem Nutzer, dass diese Daten sich, mit den Daten anderer Roboter, überschneiden.
. Das System verwirft die problematische Änderung.
. Das Use Case wird bei Schritt 3 fortgesetzt.



=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.


Der Roboter ist weiterhin eindeutig identifizierbar eingespeichert.
Der Nutzer hat das erfolgreiche Bearbeiten des Roboters bestätigt bekommen.
Die Logdatei hat Beginn des Use Cases sowie Ende und Beendigungsgrund gespeichert. 


