//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).


//Use Cases erste Überlegnung: Starten des Follow-Me, Verbindung mit Roboter herstellen, About-Button,... 
== Use-Case UC01: Speichern der Roboter

=== Kurzbeschreibung
Dieser Use Case beschreibt, wie die verschiedenen Roboter abgespeichert werden, damit diese in späteren Use Cases genutzt werden können.

=== Kurzbeschreibung der Akteure

==== Nutzer: Nutzer der App, welche neue Roboter hinzufügen möchten

==== Server: Server, auf dem die Daten des Nutzers gespeichert werden

=== Vorbedingungen
. Der zu speichernde Roboter ist erreichbar und kompatibel.
. Der Nutzer hat eine stabile GPS Verbindung sowie eine stabile Verbindung zum Server.
. Der Nutzer kennt das benötigte Token.


=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Nutzer in der App die Schaltfläche "Roboter verwalten" betätigt.
. Das System öffnet eine Liste aller gespeicherten Roboter.
. Der Nutzer wählt nun "Roboter hinzufügen" aus der Menüleiste aus.
. Das System fragt nach einem Token.
. Der Nutzer gibt das passende Token ein.
. Das System findet den Roboter und vergleicht, ob dieses Token sich bereits in der Liste der gespeicherten Roboter befindet.
. Das Token des Roboters befindet sich noch nicht in der Liste, daher speichert das System dieses und fragt den Nutzer nach einem Namen für den Roboter.
. Der Nutzer vergibt einen Namen und bestätigt diesen.
. Das System überprüft, ob der Name bereits vergeben ist.
. Der Name ist noch nicht vergeben, daher speichert das System den neuen Roboter unter dem eingegebenen Namen samt dem Token in die Liste der gespeicherten Roboter.
. Das System gibt diese Information an den Server weiter. 
. Das System lädt erneut das Menü "Roboter verwalten" und zeigt die Liste an.  


=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== System findet keinen Roboter zu diesem Token
Wenn das System in Schritt 4 keinen Roboter findet, dann

. gibt das System den Nutzer eine Fehlermeldung zurück.
. System springt in das Menü "Roboter verwalten" zurück, wo der Nutzer erneut versuchen kann, den Roboter hinzuzufügen (Siehe Schritt 3).

==== Token des Roboters befindet sich bereits in der Liste der gespeicherten Roboter
Wenn sich das Token des Roboters in Schritt 5 bereits in der Liste der gespeicherten Roboter befindet, dann

. sagt das System dem Nutzer, dass sich der Roboter bereits in der Liste befindet.
. Das System fragt den Nutzer, ob er ein anderes Token eingeben möchte oder ob er das Hinzufügen eines Roboters abbrechen möchte.
. Wenn der Nutzer ein anderes Token eingeben möchte, springt das System zu Schritt 4 des Standardablaufs.
. Wenn das Hinzufügen eines Roboters abgebrochen werden soll, springt das System zurück in das Menü "Roboter verwalten".

==== Name des Roboters ist bereits vergeben
Wenn das System feststellt, dass der vom Nutzer eingegebene Name in Schritt 8 bereits vergeben ist, dann

. System gibt dem Nutzer Fehlermeldung zurück, dass dieser Name bereits genutzt wird.
. Das System leert die Eingabe des Nutzers und fragt erneut nach einem Namen.
. Der Nutzer vergibt entweder einen neuen Namen oder bricht den Vorgang ab.
. Wenn der Nutzer einen neuen Namen vergeben möchte springt das System zu Schritt 8 des Standardablaufs.
. Wenn der Nutzer den Vorgang abbricht springt das System zurück in das Menü "Roboter verwalten".

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern

==== <Unterablauf 1>
. <Unterablauf 1, Schritt 1>
. …
. <Unterablauf 1, Schritt n>

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.

==== <Szenario 1>
. <Szenario 1, Schritt 1>
. …
. <Szenario 1, Schritt n>

=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.

==== Der Roboter befindet sich nun in der Liste der gespeicherten Roboter und kann für Aktionen der App (siehe andere Use Cases) verwendet werden.

=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.

==== <Besondere Anforderung 1>
