= Vision: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Der Zweck dieses Dokuments ist es, die wesentlichen Bedarfe und Funktionalitäten der Follow-Me Android-App zu sammeln, zu analysieren und zu definieren. Der Fokus liegt auf den Fähigkeiten, die von Stakeholdern und adressierten Nutzern benötigt werden, und der Begründung dieser Bedarfe. Die Details, wie die Follow-Me Android-App diese Bedarfe erfüllt, werden in der Use-Case und Supplementary Specification beschrieben.

=== Zweck
Der Zweck dieses Dokuments ist es, die wesentlichen Anforderungen an das System aus Sicht und mit den Begriffen der künftigen Anwender zu beschreiben.

=== Gültigkeitsbereich (Scope)
Dieses Visions-Dokument bezieht sich auf die Follow-me Android-App für Fahrroboter, welche von Team I1 entwickelt wird. Ziel des Projektes ist es, eine funktionierende App, welche via GPS Daten über eine absolvierte Route sammelt, an einen Server zum Speichern sendet und von selbigen auch Daten empfangen und auslesen kann, zu entwickeln.

=== Definitionen, Akronyme und Abkürzungen
//Verweis passend zum Belegabgabe-Template se1_belegabgabe_t00.adoc
Siehe <<#glossary, Glossar>>.

=== Referenzen
(hier externe Verweise zu anderen Dokumenten, Quellen, Standards etc. einfügen, sofern notwendig)

Für Teile der Implementierung greift das Team I1 auf die [GPS-Tracking-Android-App](https://github.com/MarioNeugebauer/GpsTrackingAndroid) zurück, welche im vorangegangenen Projektzyklus vom Team I5 entwickelt wurde. Diese App ermöglicht GPS-Tracks zu erstellen. 


== Positionierung

=== Fachliche Motivation
Der Auftraggeber sucht nach einer Funktion, um die Fahrroboter wirtschaftlich nutzbar zu machen, da diese zum jetzigen Standpunkt noch kein Use-Case als Verkaufsargument bieten. Zu bedenken ist jedoch, dass sich das autonome Fahren des Roboters zur Zeit ebenfalls in der Entwicklung befindet.

=== Problem Statement
//Stellen Sie zusammenfassend das Problem dar, das mit diesem Projekt gelöst werden soll. Das folgende Format kann dazu verwendet werden:

[cols="1,3"]
|===
| Das Problem | Die Fahrroboter können noch nicht bedient werden.
| betrifft | die Kunden, allem voran Förster und Bauern
| die Auswirkung davon ist | *•* Fahrroboter haben noch keinen praktischen nutzen

*•* den Kunden kann noch nicht schwere, körperliche Arbeit erleichtert werden
| eine erfolgreiche Lösung wäre | Eine voll funktionsfähige App, welche es ermöglicht, die Fahrroboter zu bedienen. Dadurch könnten Arbeiten, wie zum Beispiel das Tragen von schweren Gegenständen durch den Fahrroboter abgenommen werden
|===

////
Beispiel:
[cols="1,3"]
|===
|Das Problem | aktuelle Informationen zum Stundenplan und Noten einfach zu erhalten
|betrifft | Studierende der HTW Dresden
|die Auswirkung davon ist | umständliche und aufwändige Suche nach Noten, Zeiten und Räumen
|eine erfolgreiche Lösung wäre | die Zusammenführung und benutzer-individuelle Darstellung auf einem mobilen Endgerät
|===
////

=== Positionierung des Produkts
//Ein Positionierung des Produkts beschreibt das Einsatzziel der Anwendung und die Bedeutung das Projekts an alle beteiligten Mitarbeiter.

//Geben Sie in knapper Form übersichtsartig die Positionierung der angestrebten Lösung im Vergleich zu verfügbaren Alternativen dar. Das folgende Format kann dazu verwendet werden:

[cols="1,3"]
|===
| Für | Kunden, primär Förster und / oder Bauern
| die | schwere Gegenstände bzw. Ladungen transpotieren müssen
| Das Produkt / die Lösung ist ein | App, welche die Steuerung eines Fahrroboters ermöglicht
| Die | es möglich macht, schwere Lasten an den Fahrroboter zu geben und diese über ihn transpotieren zu lassen
| Im Gegensatz zu | die Last selber tragen oder von Mitarbeitern tragen zu lassen
| Unser Produkt | ermöglicht es, Kraft und Zeit zu sparen
|===

////
Beispiel Produkt:
|===
| Für | Studierende der HTW
| die | die ihren Studienalltag effizienter organisieren möchten
| Das Produkt ist eine | mobile App für Smartphones
| Die | für den Nutzer Informationen zum Stundenplan und Noten darstellt
| Im Gegensatz zu | Stundenplänen der Website und HIS-Noteneinsicht
| Unser Produkt | zeigt nur die für den Nutzer relevanten Informationen komfortabel auf dem Smartphone an.
|===
////


== Stakeholder Beschreibungen

=== Zusammenfassung der Stakeholder

[%header, cols="1,3,3"]
|===
| Name | Beschreibung | Verantwortlichkeiten

| [Benennung des Stakeholder-Typs.]
| [Kurze Beschreibung des Stakeholders.]
| [Fassen Sie die wesentlichen Verantwortlichkeiten des Stakeholder mit Bezug auf das zu entwickelnde System kurz zusammen, d.h. ihr besonderen Interessen. Beispiele: Dieser Stakeholder sorgt dafür, dass das System gewartet wird / dass die angezeigten Daten aktuell sind / überwacht den Projektfortschritt / usw.]

| Entwickler Team der App I1
| Kursteilnehmer des Moduls Software Engineering I (I150) / Requirements Engineering (I925), welche für das Projekt zuständig sind
| Erstellen der App und Server dem Bedarf anpassen

| Firma Sciota Robotics (Entwickler der Fahrroboter)
| Entwickler der Fahrroboter
| Bereitstellen der Roboter und Implementierung des autonomen Fahrens


| Kunde (Förster, Bauern)
| Kunden, welche die Fahrroboter im Berufsalltag nutzen möchten
| Nutzen der App nach Anleitung

| Auftraggeber Prof. Dr.-Ing. Mario Neugebauer
| Auftraggeber des Projektes
| Ansprechpartner für das Projekt; legt die Anforderungen fest

| HTW Dresden Rechenzentrum
| Server, auf dem die Daten zwischengespeichert werden
| Bereitstellung des benötigten Speichers; Zuverlässigkeit der Server sichern

| Gesetzgeber
| Legt Rahmenbedingungen und Vorschriften fest
| Lizensen und gesetzliche Vorschriften müssen zwingend beachtet werden

|===

=== Benutzerumgebung
Beschreiben Sie die Arbeitsumgebung des Nutzers. Hier sind einige Anregungen:

//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
. Anzahl der Kunden entspricht der Anzahl der Kunden, welche sich einen Fahrroboter zugelegt haben und die App nutzen. Dies kann sich über Zeit stark verändern.
. Die Bearbeitungsdauer hängt von den Wünschen des Kunden ab. Je länger der absolvierte Pfad, desto länger benötigt der Roboter, um ihn erneut zu absolvieren. 
. Die App ist für den Outdoor Einsatz gedacht und benötigt GPS Signal sowie eine Internetverbindung.
. Die App wird auf der aktuell gängigen Android Version 11 entwickelt. Bei viel älteren oder zukünftigen Versionen kann es zu Kompatibilitätsproblemen kommen.
. Die Daten über den absolvierten Pfad sollen auf einem Server gespeichert werden. Die App muss daher auf diesen zugreifen. 

Hier können zudem bei Bedarf Teile des Unternehmensmodells (Prozesse, Organigramme, IT-Landschaft, ...) eingefügt werden, um die beteiligten Aufgaben und Rollen zu skizzieren.


== Produkt-/Lösungsüberblick

=== Bedarfe und Hauptfunktionen
//Vermeiden Sie Angaben zum Entwurf. Nennen wesentliche Features (Produktmerkmale) auf allgemeiner Ebene. Fokussieren Sie sich auf die benötigten Fähigkeiten des Systems und warum (nicht wie!) diese realisiert werden sollen. Geben Sie die von den Stakeholdern vorgegebenen Prioritäten und das geplante Release für die Veröffentlichung der Features an.

[%header, cols="4,1,4,1"]
|===
| Bedarf | Priorität | Features | Geplantes Release
| xx | xx | xx | xx
|===


//Notiz: Karte + Anzeige, Follow-me, Hilfe, About, Daten mit Server synchronisieren

== Zusätzliche Produktanforderungen
//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren

//Notiz: Verbindung zum Roboter herstellen, Robotor aus Menge geziehlt auswählen, Aufgaben an Verbundene Roboter verteilen


Hinweise:

. Führen Sie die wesentlichen anzuwendenden Standards, Hardware oder andere Plattformanforderungen, Leistungsanforderungen und Umgebungsanforderungen auf
. Definieren Sie grob die Qualitätsanforderungen für Leistung, Robustheit, Ausfalltoleranz, Benutzbarkeit und ähnliche Merkmale, die nicht von den genannten Features erfasst werden.
. Notieren Sie alle Entwurfseinschränkungen, externe Einschränkungen, Annahmen oder andere Abhängigkeiten, die wenn Sie geändert werden, das Visions-Dokument beeinflussen. Ein Beispiel wäre die Annahme, dass ein bestimmtes Betriebssystem für die vom System erforderliche Hardware verfügbar ist. Ist das Betriebssystem nicht verfügbar, muss das Visions-Dokument angepasst werden.
. Definieren Sie alle Dokumentationsanforderugen, inkl. Benutzerhandbücher, Onlinehilfe, Installations-, Kennzeichnungs- und Auslieferungsanforderungen-
. Definieren Sie die Priorität für diese zusätzlichen Produktanforderungen. Ergänzen Sie, falls sinnvoll, Angaben zu Stabilität, Nutzen, Aufwand und Risiko für diese Anforderungen.

[%header, cols="4,1,1"]
|===
| Anforderung | Priorität | Geplantes Release
| xx | xx | xx
|===
