//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).


//Use Cases erste Überlegnung: Starten des Follow-Me, Verbindung mit Roboter herstellen, About-Button,... 
== Use-Case: Beenden der Follow-Me Funktion

=== Kurzbeschreibung
Dieses Use Case beschreibt das Beenden der Follow me Funktion um einen Roboter nicht länger dem Nutzer folgen zu lassen.

=== Kurzbeschreibung der Akteure

==== Nutzer (User)
    Der Nutzer ist der Hauptakteur in diesem Use Case, durch ihn wird das Use Case aufgerufen und gestartet.

==== Anwendung
    Die Anwendung dient dem Nutzer als grafische Oberfläche um Aktionen durchzuführen und Entscheidungen zu treffen. Außerdem übermittelt sie im Hintergrund die nötigen Daten an den Server.

==== Server
    Der Server empfängt die Daten durch die Anwendung und leitet diese an den jeweiligen Roboter weiter. Er dient als Schnittstelle der Akteure.

==== Roboter
    Er empfängt Signale und gibt Rückmeldung über den Erhalt der Signale.

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

==== Internetverbindung
Die untereinander kommunizierenden Akteure (Anwendung, Server, Roboter) benötigen eine stabile Internetverbindung.

==== GPS Verbindung
Der Nutzer und der ausgewählte Roboter benötigen eine stabile GPS Verbindung.

==== Roboter existent
Es wurden bereits Roboter gespeichert.

==== Roboter verfügbar
Es existiert ein Roboter, der die Follow me Funktion ausführt.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Das Use Case beginnt, wenn der Nutzer die Schaltfläche "Follow Me" betätigt.
. Das System zeigt dem Nutzer eine Liste aller Roboter die den Follow me Befehl ausführen.
. Der Nutzer wählt einen Roboter aus der Liste der Roboter.
. Das System fragt erneut ob die Follow Me Funktion wirklich beendet werden soll.
. Der Nutzer bestätigt erneut, dass die Follow Me Funktion beendet werden soll.
. Das System teilt dem Roboter mit dem Nutzer nicht länger zu folgen.
. Das System zeigt dem Nutzer, dass der ausgewählte Roboter ihm nun nicht mehr folgt.
. Das Use Case endet erfolgreich, das Use Case 06 "Speichern der Route" beginnt.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== Nutzer möchte Follow Me Funktion doch nicht beenden
Falls der Nutzer in Schritt 5 auswählt, dass die Follow Me Funktion nicht beendet werden soll

. Das System zeigt dem Nutzer an, dass die Follow Me Funktion nicht beendet wurde.
. Das Use Case endet erfolglos, das System zeigt dem Nutzer die Lister der Roboter an.


==== Der Nutzer möchte die Änderungen nicht übernehmen
Falls der Nutzer in Schritt 6 die Änderungen nicht übernehmen möchte

. Der Nutzer bestätigt nicht, dass er die Daten ändern möchte.
. Das System verwirft die Änderungen.
. Das Use Case endet erfolglos, dem Nutzer wird erneut die Liste der Roboter angezeigt.

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern

==== <Unterablauf 1>
. <Unterablauf 1, Schritt 1>
. …
. <Unterablauf 1, Schritt n>

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.

==== Erfolgreiches beenden
Der Roboter führt die Follow-me Funktion nicht länger aus und folgt dem Nutzer nicht mehr. Der Nutzer sieht die Liste der Roboter.

==== Erfolgloses beenden
Der Roboter führt die Follow-me Funktion weiterhin aus und folgt dem Nutzer. Der Nutzer sieht die Liste der Roboter.

==== Der Nutzer bricht das Use Case ab
Der Roboter führt die Follow-me Funktion weiterhin aus. Der Nutzer sieht die Liste der Roboter.

=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.

==== Roboter Aktion 
Der Roboter führt keine Funktion aus.

==== Logdatei aktualisiert
Die Logdatei hat Beginn des Use Cases sowie Ende und Beendigungsgrund gespeichert. 

==== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.

=== Usability
Erlernbarkeit: Das Beenden der Follow Me Funktion ist eine grundlegende Funktion des Systems und soll intuitiv und linear funktionieren.
