//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).


//Use Cases erste Überlegnung: Starten des Follow-Me, Verbindung mit Roboter herstellen, About-Button,... 
== Use-Case: Bearbeiten einer Route

=== Kurzbeschreibung
Dieses Use Case beschreibt das Bearbeiten einer Route um zum Beispiel den Namen anzupassen.

=== Kurzbeschreibung der Akteure

==== Nutzer (User)

    Der Nutzer ist der Hauptakteur in diesem Use Case, durch ihn wird das Use Case aufgerufen und gestartet.

==== Anwendung

    Die Anwendung dient dem Nutzer als grafische Oberfläche um Aktionen durchzuführen und Entscheidungen zu treffen. Außerdem übermittelt sie im Hintergrund die nötigen Daten an den Server.

==== Server

    Der Server empfängt die Daten durch die Anwendung und speichert diese. Er dient außerdem als Schnittstelle der Akteure.


=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

==== Internetverbindung
Die untereinander kommunizierenden Akteure (Anwendung, Server) benötigen eine stabile Internetverbindung.

==== Routen verfügbar
Es befinden sich bereits Routen in der Liste der gespeicherten Routen.


=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Nutzer in der App eine Route aus der Liste der Routen auswählt.
. Das System zeigt dem Nutzer alle zu der ausgewählten Route verfügbaren Daten an (Name, Token etc.)
. WHILE Nutzer möchte Änderung der Daten vornehmen.
.. Der Nutzer drückt auf die Daten, die zu ändern sind. 
.. Der Nutzer ändert die Daten.
. Der Nutzer wählt die Schaltfläche "Änderungen Speichern".
. Das System zeigt dem Nutzer alle Daten die geändert werden.
. Der Nutzer bestätigt erneut, dass er die Daten ändern möchte.
. Das System ändert die Daten der ausgewählten Route.
. Das System zeigt dem Nutzer die geänderten Daten an.
. Das Use Case endet erfolgreich, dem Nutzer wird erneut die Liste der Routen angezeigt.



=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== Der Nutzer möchte die Änderungen nicht übernehmen
Falls der Nutzer in Schritt 6 die Änderungen nicht übernehmen möchte

. Der Nutzer bestätigt nicht, dass er die Daten ändern möchte.
. Das System verwirft die Änderungen.
. Das Use Case endet erfolglos, dem Nutzer wird erneut die Liste der Routen angezeigt.


==== Geänderte Daten sind bereits an einen anderen Roboter vergeben
Falls der Nutzer in Schritt 4 Daten so geändert hat, dass diese sich mit den Daten anderer Routen überschneiden (zum Beispiel: Name)

. Das System zeigt dem Nutzer, dass diese Daten sich, mit den Daten anderer Routen, überschneiden.
. Das System verwirft die problematische Änderung.
. Das Use Case wird bei Schritt 3 fortgesetzt.


=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern


=== Wesentliche Szenarios

==== Erfolgreiches beenden
Der Roboter wurde erfolgreich bearbeitet, die Daten sind geändert und werden bei Auswahl und Verwendung des Roboters fehlerfrei angezeigt.

==== Erfolgloses beenden
Der Roboter wurde nicht bearbeitet, bei Auswahl und Verwendung des Roboters werden die ursprünglichen Daten angezeigt.

==== Der Nutzer bricht das Use Case ab
Bereits gesammelte Daten werden verworfen, bei Auswahl und Verwendung des Roboters werden die ursprünglichen Daten angezeigt.

==== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.

=== Roboter identifizierbar
Der Roboter ist weiterhin eindeutig identifizierbar eingespeichert.

=== Bestätigung an Nutzer
Der Nutzer hat das erfolgreiche Bearbeiten des Roboters bestätigt bekommen.

=== Logdatei aktualisiert
Die Logdatei hat Beginn des Use Cases sowie Ende und Beendigungsgrund gespeichert. 


=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.

==== <Besondere Anforderung 1>
