//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).


//Use Cases erste Überlegnung: Starten des Follow-Me, Verbindung mit Roboter herstellen, About-Button,... 
== Use-Case: Löschen eines Roboters

=== Kurzbeschreibung
Dieser Use Case beschreibt die Auswahl des zu steuernden Roboters. Der ausgewählte Roboter wird in späteren Use Cases (siehe z.B. UC04) genutzt. 

=== Kurzbeschreibung der Akteure

==== Nutzer (User)

    Der Nutzer ist der Hauptakteur in diesem Use Case, durch ihn wird das Use Case aufgerufen und gestartet.

==== Anwendung

    Die Anwendung dient dem Nutzer als grafische Oberfläche um Aktionen durchzuführen und Entscheidungen zu treffen. Außerdem übermittelt sie im Hintergrund die nötigen Daten an den Server.

==== Server

    Der Server empfängt die Daten durch die Anwendung und leitet diese an den jeweiligen Roboter weiter. Er dient als Schnittstelle der Akteure.


=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...


=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Nutzer in der App einen Roboter aus der Liste der Roboter auswählt.
. Das System zeigt dem Nutzer alle zu dem ausgewählten Roboter verfügbaren Daten an (Name, Token etc.)
. Der Nutzer wählt die Schaltfläche "Roboter löschen" aus.
. Das System fragt den Nutzer, ob der Roboter wirklich gelöscht werden soll.
. Der Nutzer bestätigt, dass er den Roboter löschen möchte.
. Das System löscht den ausgewählten Roboter.
. Das Use Case endet erfolgreich, dem Nutzer wird erneut die Liste der Roboter angezeigt.


=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== Der Nutzer möchte den Roboter nicht löschen
Falls der Nutzer in Schritt 5 den Roboter nicht löschen möchte.

. Der Nutzer bestätigt nicht, dass er den Roboter löschen möchte.
. Das System nimmt keine Änderung vor.
. Das Use Case endet erfolglos, dem Nutzer wird erneut die Liste der Roboter angezeigt.


==== Der ausgewählte Roboter führt eine Aktion aus
Falls der in Schritt 3 ausgewählte Roboter eine Aktion ausführt.

. Das System zeigt dem Nutzer, dass der ausgewählte Roboter im Moment eine Aktion ausführt.
. Das System fragt, ob die Aktion abgebrochen werden soll.
. IF Nutzer wählt aus, dass die Aktion abgebrochen werden soll.
.. Das System bricht die Aktion des Roboters ab.
.. Das Use Case wird bei Schritt 4 fortgesetzt.
. ELSE 
.. Das System zeigt dem Nutzer, dass die Aktion des Roboters nicht abgebrochen wurde.
.. Das Use Case endet erfolglos, dem Nutzer wird erneut die Liste der Roboter angezeigt.

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern

==== <Unterablauf 1>
. <Unterablauf 1, Schritt 1>
. …
. <Unterablauf 1, Schritt n>

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.

==== Erfolgreiches beenden
Der Roboter wurde erfolgreich gelöscht, der Roboter wird nicht mehr in der Liste der Roboter angezeigt.

==== Erfolgloses beenden
Der Roboter wurde nicht gelöscht und befindet sich weiterhin unverändert in der Liste der Roboter.

==== Der Nutzer bricht das Use Case ab
Der Roboter wurde nicht gelöscht und befindet sich weiterhin unverändert in der Liste der Roboter.


=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.

==== Roboter gelöscht
Alle dem Roboter zugehörigen Daten sind auf dem Gerät des Nutzer sowie in der Datenbank des Servers gelöscht. Der Roboter befindet sich nicht länger in der Liste der Roboter.

==== Bestätigung an Nutzer
Der Nutzer hat das erfolgreiche Löschen des Roboters bestätigt bekommen.

==== Logdatei aktualisiert
Die Logdatei hat Beginn des Use Cases sowie Ende und Beendigungsgrund gespeichert. 

=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.

==== <Besondere Anforderung 1>
