//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).


//Use Cases erste Überlegnung: Starten des Follow-Me, Verbindung mit Roboter herstellen, About-Button,... 
== Use-Case: Starten der Follow me Funktion

=== Kurzbeschreibung
Dieses Use Case beschreibt das Starten der Follow me Funktion um einen Roboter dem Nutzer folgen zu lassen.

=== Kurzbeschreibung der Akteure

==== Nutzer (User)
    Der Nutzer ist der Hauptakteur in diesem Use Case, durch ihn wird das Use Case aufgerufen und gestartet.

==== Anwendung
    Die Anwendung dient dem Nutzer als grafische Oberfläche um Aktionen durchzuführen und Entscheidungen zu treffen. Außerdem übermittelt sie im Hintergrund die nötigen Daten an den Server.

==== Server
    Der Server empfängt die Daten durch die Anwendung und leitet diese an den jeweiligen Roboter weiter. Er dient als Schnittstelle der Akteure.

==== Roboter
    Er empfängt Signale und gibt Rückmeldung über den Erhalt der Signale.


=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

==== Internetverbindung
Die untereinander kommunizierenden Akteure (Anwendung, Server, Roboter) benötigen eine stabile Internetverbindung.

==== GPS Verbindung
Der Nutzer und der ausgewählte Roboter benötigen eine stabile GPS Verbindung.

==== Roboter existent
Es wurden bereits Roboter gespeichert.

==== Roboter verfügbar
Ein Roboter ist verfügbar (führt keine anderen Aktionen aus).

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")


. Das Use Case beginnt, wenn der Nutzer die Schaltfläche "Follow Me" betätigt.
. Das System zeigt dem Nutzer eine Liste aller Roboter.
. Der Nutzer wählt einen Roboter aus der Liste aller Roboter.
. Das System teilt dem Roboter mit dem Nutzer zu folgen.
. Das System zeigt dem Nutzer, dass der ausgewählte Roboter ihm nun folgt.
. Das Use Case endet, wenn dem Nutzer die Liste der Roboter angezeigt wird.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== Der ausgewählte Roboter führt eine Aktion aus
Falls der in Schritt 3 ausgewählte Roboter eine Aktion ausführt.

. Das System zeigt dem Nutzer, dass der ausgewählte Roboter im Moment eine Aktion ausführt.
. Das System fragt, ob die Aktion abgebrochen werden soll.
. IF Nutzer wählt aus, dass die Aktion abgebrochen werden soll.
.. Das System bricht die Aktion des Roboters ab.
.. Das Use Case wird bei Schritt 4 fortgesetzt.
. ELSE
.. Das System zeigt dem Nutzer, dass die Aktion des Roboters nicht abgebrochen wurde.
.. Das Use Case endet erfolglos, dem Nutzer wird erneut die Liste der Roboter angezeigt.

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern



=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.

==== Erfolgreiches Starten der Follow-me Funktion
Der Nutzer sieht die Liste seiner angelegten Roboter (Roboter 1, Roboter 2, etc.). Er wählt Roboter 2 aus und bekommt bestätigt, dass der Roboter ihm nun erfolgreich folgt.

==== Erfolgloses Starten der Follow-me Funktion
Der Nutzer sieht die Liste seiner angelegten Roboter (Roboter 1, Roboter 2, etc.). Er wählt Roboter 2 aus und bekommt angezeigt, dass Roboter 2 bereits eine andere Funktion ausführt. Er entscheidet sich, die Funktion nicht zu unterbrechen. Der Prozess wird erfolglos beendet, der Roboter folgt dem Nutzer nicht.


==== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.

Der ausgewählte Roboter folgt dem Nutzer.\n
Die Logdatei hat Beginn des Use Cases sowie Ende und Beendigungsgrund gespeichert. 

=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.

==== <Besondere Anforderung 1>

=== Usability 
Erlernbarkeit: Das Starten der Follow Me Funktion ist eine grundlegende Funktion des Systems und soll intuitiv und linear funktionieren.
