//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).


//Use Cases erste Überlegnung: Starten des Follow-Me, Verbindung mit Roboter herstellen, About-Button,... 
== Use-Case: Ablaufen einer Route

=== Kurzbeschreibung
//<Kurze Beschreibung des Use Case>
Dieses Use Case beschreibt das Starten des Roboters der eine vorausgesetzte Route ablaufen soll.


=== Kurzbeschreibung der Akteure

==== Nutzer (User)
    Der Nutzer ist der Hauptakteur in diesem Use Case, durch ihn wird das Use Case aufgerufen und gestartet.

==== Anwendung
    Die Anwendung dient dem Nutzer als grafische Oberfläche um Aktionen durchzuführen und Entscheidungen zu treffen. Außerdem übermittelt sie im Hintergrund die nötigen Daten an den Server.

==== Server
    Der Server empfängt die Daten durch die Anwendung und leitet diese an den jeweiligen Roboter weiter. Er dient als Schnittstelle der Akteure.

==== Roboter
    Er empfängt Signale und gibt Rückmeldung über den Erhalt der Signale.



=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

==== Internetverbindung
Die untereinander kommunizierenden Akteure (Anwendung, Server, Roboter) benötigen eine stabile Internetverbindung.

==== Roboter existent
Es wurden bereits Roboter gespeichert.

==== Roboter verfügbar
Ein Roboter ist verfügbar (führt keine anderen Aktionen aus).

==== Routen verfügbar
Es befinden sich bereits Routen in der Liste der gespeicherten Routen.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Nutzer in der App eine Route aus der Liste der Routen auswählt.
. Das System zeigt dem Nutzer alle zu der ausgewählten Route verfügbaren Daten an (Name, Token etc.)
. Der Nutzer betätigt die Schaltfläche "Route ablaufen".
. Das System zeigt dem Nutzer die Liste aller Roboter an.
. Der Nutzer wählt einen Roboter aus der Liste aller Roboter aus.
. Das System fragt den Nutzer erneut, ob der ausgewählte Roboter die ausgewählte Route ablaufen soll.
. Der Nutzer bestätigt. 
. Das System übermittelt die Anweisung an den Roboter
. Das System bestätigt das erfolgreiche Starten der Funktion.
. Das Use Case endet erfolgreich, dem Nutzer wird erneut die Liste der Routen angezeigt.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== Der ausgewählte Roboter führt eine Aktion aus
Falls der in Schritt 5 ausgewählte Roboter eine Aktion ausführt.

. Das System zeigt dem Nutzer, dass der ausgewählte Roboter im Moment eine Aktion ausführt.
. Das System fragt, ob die Aktion abgebrochen werden soll.
. IF Nutzer wählt aus, dass die Aktion abgebrochen werden soll.
.. Das System bricht die Aktion des Roboters ab.
.. Das Use Case wird bei Schritt 4 fortgesetzt.
. ELSE
.. Das System zeigt dem Nutzer, dass die Aktion des Roboters nicht abgebrochen wurde.
.. Das Use Case endet erfolglos, dem Nutzer wird erneut die Liste der Routen angezeigt.

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern

==== <Unterablauf 1>
. <Unterablauf 1, Schritt 1>
. …
. <Unterablauf 1, Schritt n>

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.

==== Erfolgreiches beenden
Der Roboter läuft nun die Route ab.

==== Erfolgloses beenden
Der Roboter läuft die Route nicht abund ist bereit, eine andere Aktion auszuführen, beziehungsweise fortzuführen. Der Nutzer sieht die Liste der Routen.

==== Der Nutzer bricht das Use Case ab
Der Roboter läuft die Route nicht abund ist bereit, eine andere Aktion auszuführen, beziehungsweise fortzuführen. Der Nutzer sieht die Liste der Routen.

=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.

==== Roboter Aktion 
Der Roboter läuft die Route ab.

==== Logdatei aktualisiert
Die Logdatei hat Beginn des Use Cases sowie Ende und Beendigungsgrund gespeichert. 


=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.

=== Usability 
Erlernbarkeit: Das Ablaufen einer Route ist eine grundlegende Funktion des Systems und soll intuitiv und linear funktionieren.
