//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).


//Use Cases erste Überlegnung: Starten des Follow-Me, Verbindung mit Roboter herstellen, About-Button,... 
== Use-Case: Beenden der Follow-Me Funktion

=== Kurzbeschreibung
Dieses Use Case beschreibt das Beenden der Follow me Funktion um einen Roboter nicht länger dem Nutzer folgen zu lassen.

=== Kurzbeschreibung der Akteure

==== Nutzer (User)
    Der Nutzer ist der Hauptakteur in diesem Use Case, durch ihn wird das Use Case aufgerufen und gestartet.

==== Anwendung
    Die Anwendung dient dem Nutzer als grafische Oberfläche um Aktionen durchzuführen und Entscheidungen zu treffen. Außerdem übermittelt sie im Hintergrund die nötigen Daten an den Server.

==== Server
    Der Server empfängt die Daten durch die Anwendung und leitet diese an den jeweiligen Roboter weiter. Er dient als Schnittstelle der Akteure.

==== Roboter
    Er empfängt Signale und gibt Rückmeldung über den Erhalt der Signale.

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

==== Internetverbindung
Die untereinander kommunizierenden Akteure (Anwendung, Server, Roboter) benötigen eine stabile Internetverbindung.

==== GPS Verbindung
Der Nutzer und der ausgewählte Roboter benötigen eine stabile GPS Verbindung.

==== Roboter existent
Es wurden bereits Roboter gespeichert.

==== Roboter verfügbar
Es existiert ein Roboter, der die Follow me Funktion ausführt.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Das Use Case beginnt, wenn der Nutzer die Schaltfläche "Follow Me" betätigt.
. Das System zeigt dem Nutzer eine Liste aller Roboter die den Follow me Befehl ausführen.
. Der Nutzer wählt einen Roboter aus der Liste der Roboter.
. Das System fragt erneut ob die Follow Me Funktion wirklich beendet werden soll.
. Der Nutzer bestätigt erneut, dass die Follow Me Funktion beendet werden soll.
. Das System teilt dem Roboter mit dem Nutzer nicht länger zu folgen.
. Das System zeigt dem Nutzer, dass der ausgewählte Roboter ihm nun nicht mehr folgt.
. Das Use Case endet erfolgreich, das Use Case 06 "Speichern der Route" beginnt.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

==== Nutzer möchte Follow Me Funktion doch nicht beenden
Falls der Nutzer in Schritt 5 auswählt, dass die Follow Me Funktion nicht beendet werden soll

. Das System zeigt dem Nutzer an, dass die Follow Me Funktion nicht beendet wurde.
. Das Use Case endet erfolglos, das System zeigt dem Nutzer die Liste der Roboter an.


==== Kein Roboter führt die Follow-me Funktion aus
Falls das System in Schritt 2 keine Roboter anzeigt, da keiner die Follow-me Funktion ausführt

. Das System zeigt dem Nutzer, dass keiner der Roboter die Follow-me Funktion ausführt.
. Das Use Case endet erfolglos, Das System zeigt dem Nutzer die Liste der Roboter an.


=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.


==== Erfolgreiches Beenden der Follow-me Funktion
Der Nutzer sieht die Liste aller Roboter, die im Moment die Follow-me Funktion ausführen (Roboter 2). Er wählt Roboter 2 aus und und bestätigt erneut, dass dieser die Follow-me Funktion nicht länger ausführen soll. Der Nutzer bekommt bestätigt, dass der Roboter ihm nun nicht länger folgt.

==== Erfolgloses Beenden der Follow-me Funktion
Der Nutzer sieht die Fehlermeldung, dass keiner der eingespeicherten Roboter im Moment die Follow-me Funktion ausführen. Der Prozess wird erfolglos beendet.


==== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.

Der ausgewählte Roboter folgt dem Nutzer nicht länger.

Es wird in der Liste der Roboter angezeigt, dass der ausgewählte Roboter keine Funktion ausführt.

Die Logdatei hat Beginn des Use Cases sowie Ende und Beendigungsgrund gespeichert. 


==== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.

=== Usability
Erlernbarkeit: Das Beenden der Follow Me Funktion ist eine grundlegende Funktion des Systems und soll intuitiv und linear funktionieren.
