= Architecture Notebook: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Zweck
Dieses Dokument beschreibt die Philosophie, Entscheidungen, Nebenbedingungen, Begründungen, wesentliche Elemente und andere übergreifende Aspekte des Systems, die Einfluss auf Entwurf und Implementierung haben.

//Hinweise: Bearbeiten Sie immer die Abschnitte 2-6 dieser Vorlage. Nachfolgende Abschnitte sind empfohlen, aber optional und sollten je nach Umfang der künftigen Wartungsarbeiten, Fähigkeiten des Entwicklungsteams und Bedeutung anderer architektureller Belange.

//Anmerkung: Die Architektur legt wesentliche EINSCHRÄNKUNGEN für den Systementwurf fest und ist ein Schlüssel für die Erfüllung nicht-funktionaler Eigenschaften!


== Architekturziele und Philosophie

Das System besteht aus einer Android-App, sie dient dem Nutzer als grafische Oberfläche um Aktionen durchzuführen und Entscheidungen zu treffen. Außerdem übermittelt sie im Hintergrund die nötigen Daten an den Server. Einem Simulationssystem und einem Server, der GPS-Tracks speichert sowie Daten durch die Anwendung empfängt und diese an den jeweiligen Roboter weiterleitet. Er dient als Schnittstelle der Akteure. Um die Roboter zu synchronisieren muss einmalig dem Gerät ein Token von einem Admin zugewiesen werden. Die App soll nicht im PlayStore veröffentlicht werden und vorerst nur von einer Person genutzt werden, aber nahezu rund um die Uhr verfügbar sein und später auch Mehrbenutzerbetrieb ermöglichen. Bei den verwendeten Endgeräten handelt es sich um Android Smartphones, die über einen Touchscreen bedient werden. Die technische Ausstattung (Bildschirmgröße, RAM, CPU, Bandbreite) sowie die genaue Android Version sind unbekannt. Ausgegangen wird für die Entwicklung von der derzeit gängigen Android Version 11.

Für den Server wird ein Ubuntu Server mit einer mySQL/mSQL basierten Datenbank verwendet. Er muss auch außerhalb des HTW-Netzes erreichbar sein. 

Die App soll eine möglichst intuitive Benutzeroberfläche besitzen und in Aktionen durch bekannte Icons oder Begriffe einfach beschrieben werden.

Das System ist die initiale Version und wird vermutlich im Laufe der Zeit noch hinsichtlich verschiedener Aspekte erweitert werden. Dazu gehören z.B. die Optimierung des Mehrbenutzerbetriebs und die Erweiterung der angebotenen Routenoptionen.


//Hinweise: Beschreiben Sie die Philosophie der Architektur, d.h. den zentralen Ansatz für ihre Architektur. Identifizieren Sie alle Aspekte, die die Philosophie beeinflussen, z.B. komplexe Auslieferung Aspekte, Anpassung von Altsystemen oder besondere Geschwindigkeitsanforderungen. Muss es besonders robust sein, um eine langfristige Wartung und Pflege zu ermöglichen?

//Formulieren Sie eine Reihe von Zielen, die die Architektur in ihrer Struktur und ihrem Verhalten erfüllen muss. Identifizieren Sie kritische Fragen, die von der Architektur adressiert werden müssen, z.B. besondere Hardware-Abhängigkeiten, die vom Rest des Systems isoliert werden sollten oder Sicherstellung der Funktionsfähigkeit unter besonderen Bedingungen (z.B. Offline-Nutzung).


== Annahmen und Abhängigkeiten

Annahmen: ::

* Auf dem Smartphone des Benutzers ist eine der neuesten Android Versionen installiert 
* Der Benutzer besitzt ein stabile GPS-Verbindung.
* Der Benutzer besitzt eine stabile Internetverbindung.
* Der Benutzer hat der App alle benötigten Berechtigungen erteilt.
* Die verwendeten Frameworks und APIs funktionieren nahezu fehlerfrei und werden in Zukunft gepflegt.

Abhängigkeiten: ::

* Wir sind drauf angewiesen, dass der Kartendaten Provider weiter kostenlos Kartendaten zu Verfügung stellt und nahezu rund um die Uhr erreichbar ist.
* Wir sind von unserem Rechenzentrum abhängig, da der Server zur Synchronisation jederzeit zur Verfügung stehen muss.
* Wir sind darauf angewiesen, dass alle eingesetzten Frameworks und APIs gepflegt werden.


//[List the assumptions and dependencies that drive architectural decisions. This could include sensitive or critical areas, dependencies on legacy interfaces, the skill and experience of the team, the availability of important resources, and so forth]


== Architektur-relevante Anforderungen

Functional: ::
* SWFA-1: Die GPS-Tracks müssen dauerhaft gespeichert und bei Bedarf aktualisiert sein. Wenn ein aufgenommenener GPS-Track hochgeladen wird, ist dieser dann dauerhaft verfügbar 
* SWFA-2: Während der Nutzung der App muss dauerhaft eine Internetverbindung bzw. Verbindung zum Server bestehen. 

Effizienz (Perfomance): ::

* NFAP-2: Gewählte Aktionenen der App sollen innerhalb von 1000 Millisekunden an den Server gesendet, verarbeitet und verifiziert werden.

* NFAP-3: Die Speicherung der Daten auf dem Server soll nicht länger als 5 Sekunden dauern

Wartbarkeit (Supportability): ::
* NFAS-1: Die App soll entwicklungsrelevante Systemfehler loggen und an die Entwickler schicken


//Fügen Sie eine Referenz / Link zu den Anforderungen ein, die implementiert werden müssen, um die Architektur zu erzeugen.


== Entscheidungen, Nebenbedingungen und Begründungen
//[List the decisions that have been made regarding architectural approaches and the constraints being placed on the way that the developers build the system. These will serve as guidelines for defining architecturally significant parts of the system. Justify each decision or constraint so that developers understand the importance of building the system according to the context created by those decisions and constraints. This may include a list of DOs and DON’Ts to guide the developers in building the system.]

. Entscheidung oder Einschränkung oder Begründung 1
. Entscheidung oder Einschränkung oder Begründung 2


== Architekturmechanismen
https://www2.htw-dresden.de/~anke/openup/core.tech.common.extend_supp/guidances/concepts/arch_mechanism_2932DFB6.html[Doku "Concept: Architectural Mechanism"]
//[List the architectural mechanisms and describe the current state of each one. Initially, each mechanism may be only name and a brief description. They will evolve until the mechanism is a collaboration or pattern that can be directly applied to some aspect of the design.]

//Beispiele: relationales DBMS, Messaging-Dienste, Transaktionsserver, Webserver, Publish-Subscribe Mechanismus

//Beschreiben Sie den Zweck, Eigenschaften und Funktion der Architekturmechanismen.

. Architekturmechanismus 1
. Architekturmechanismus 2


== Architektursichten (Views)
//[Describe the architectural views that you will use to describe the software architecture. This illustrates the different perspectives that you will make available to review and to document architectural decisions.]

Folgende Sichten werden empfohlen:

=== Logische Sicht
//Beschreibt die Struktur und das Verhalten Systemteilen, die hohen Einfluss auf die Architektur haben. Dies kann die Paketstruktur, kritische Schnittstellen, wichtige Klassen und Subsysteme sowie die Beziehungen zwischen diesen Elementen enthalten. Zudem sollten die physische und logische Sicht persistenter Daten beschrieben werden, wenn es diesen Aspekt im System gibt. Dies ist ein hier dokumentierter Teilaspekt des Entwurfs.

=== Physische Sicht (Betriebssicht)
//Beschreibt die physischen Knoten (Rechner) des Systems, der Prozesse, Threads und Komponenten, die in diesen Knoten ausgeführt werden. Diese Sicht wird nicht benötigt, wenn das System in einem einzelnen Prozess oder Thread ausgeführt wird.

=== Use cases
//Eine Liste oder ein Diagramm der Use Cases, die architektur-relevante Anforderungne enthalten.
