= Projektplan: {project-name}
Carl Ulrich Brinker <carlulrich.brinker@htw-dresden.de>; Leon Lowa <leon.lowa@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Im Folgenden werden die Arbeitsweisen für das Projekt I1 beschrieben und erklärt. Dabei ist der Projektplan ein Anhaltspunkt zur Erfüllung der Projektziele. Das Team orientiert sich bei diesem Projekt am Vorgehensmodell „Open Unified Process“. 
Das Projekt umfasst die vier Phasen:

*  Inception (2 Iterationen)
*  Elaboration (3 Iterationen)
*  Construction (5 Iterationen)
*  Transition (2 Iterationen)

Der Projektplan wird während der Projektlaufzeit ergänzt und verfeinert. Verantwortlich dafür sind die Projektleiter.



== Projektorganisation
//Introduce the project team, team members, and roles that they play during this project. If applicable, introduce work areas, domains, or technical work packages that are assigned to team members. Introduce neighboring projects, relationships, and communication channels. If the project is introduced somewhere else, reference that location with a link.
Die internen Stakeholder werden in der Rollenübersicht vorgestellt. Hier ist eine ausführliche Auflistung der einzelnen Stakeholder und deren Rolle innerhalb des Teams zu finden.

[%header, cols="1,3a,2,1"]
|===
| Name
| Rolle
| Studium
| Vorkenntnisse

| Carl Ulrich Brinker
| Project Manager
| Wirtschaftsingenieurwesen
| Projectmanagement

| Leon Lowa
| Project Manager, Developer
| Wirtschaftsinformatik
| Java, Python, C

| Marcel Axmann
| Tester, Analyst
| Informatik
| Java, C/C++

| Jonas Pfeiffer
| Developer
| Wirtschaftsinformatik
| Java, C, SQL

| Manuel Scheer
| Analyst
| Wirtschaftsinformatik
| Projektmanagement, Java, C

| Magnus Böhne
| Architect
| Wirtschaftsinformatik
| C, C#, C++, Java, Kotlin, Go

| Michael Novak
| Tester
| Wirtschaftsinformatik
| Java, C, SQL

|===



=== Arbeitsweise

Die Kommunikation lief sowohl über die Anwendungen WhatsApp und Discord als auch in Präsenz ab. Die Aufgabenverteilung wurde anfangs nur über Discord besprochen und später zudem über GitHub-Issues verwaltet.

Im wöchentlichen Montags-Meeting wurden neue Aufgaben verteilt, Aufgaben umgeschichtet und der Arbeitsstand verglichen. Aufgaben wurden vom Projekt Manager und Stellvertretung am Tag zuvor ausgearbeitet. Die Agenda wurden zudem am Tag davor über die Anwendung WhatsApp bekannt gegeben. Im Montags-Meeting wurden die bearbeiten Aufgaben besprochen und mögliche Probleme oder Fragestellungen im Team diskutiert. Aus diesen Meetings wird ein Protokoll angefertigt, welches anschließen in das ASCII-Format übertragen und in das GitHub-Repository hinzugefügt wird. Nach erfolgreicher Beendigung von Aufgaben, werden diese zum Review durch ein anderes Teammitglied freigegeben.
Zur Bearbeitung der Aufgaben wurden den Teammitgliedern Zuständigkeitsrollen zugeteilt, wobei sich jedoch darauf verständigt wurde, dass die Aufgabenverteilung nicht den festgelegten Rollen entsprechen müssen, was eine agile Aufgabenverteilung ermöglicht. Dieses Konzept ermöglicht den Teammitgliedern eine vollständige Transparenz über das Projekt, dessen Aufgaben und deren Arbeitsstand.

Die Aufgabenübersicht in GitHub-Issues erfolgt über ein definiertes Label System. So werden Aufgaben, direkt nach Erstellung, zunächst mit einem Deadline-Label versehen, welches die Deadline der jeweiligen Aufgabe angibt. Wurde die Aufgabe angefangen, wird das Issue mit dem Label "in Bearbeitung versehen". Ist die Aufgabe abgeschlossen, ist sie bereit zum Review, was ebenfalls mit entsprechenden Labels symbolisiert wird. Nach Beendigung der Aufgabe und erfolgreichem Review, kann das Issue schlussendlich geschlossen werden. 

Die Aufgaben werden, so weit wie möglich, in Zweierteams aufgeteilt, um eine differenziertere Sichtweise zu erreichen.


== Praktiken und Bewertung
//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).
=== Management Practices
https://www2.htw-dresden.de/~anke/openup/publish.openup.base/customcategories/management_practice_list_8D917129.html?nodeId=770581c6[Management Practices OpenUP]

Nach Vorgabe der Lehrveranstaltung wurde als Managementmethode der Open Unified Process verwendet. Hierbei werden Meilensteine in Iterationen erreicht. Diese Meilensteine werden in kleinere Aufgaben/Teilschritte unterteilt, durchgeführt und gegebenenfalls erweitert. Resultierend können etwaig auftretende Probleme schnell erkannt und gelöst und falsche Entscheidungen rechtzeitig identifiziert und gegengesteuert werden.

Unser Team führt Iterationen in 14-tägigen Zyklen durch, wobei wir jedoch jede Woche ein Meeting durchführen. In unseren Montags-Meetings werden vorherige Aufgaben besprochen, neue Aufgaben zugeteilt und neu aufgekommene Fragen besprochen oder zur Absprache mit dem Kunden notiert. Es gibt einen Meetingsleiter, welcher das Team durch die Agenda führt und einen Protokollführer. Der Projektmanager und sein Stellvertreter besprechen am Vortag alle anstehenden Aufgaben und erstellen eine Agenda. Diese wird vor dem Montags-Meeting an alle Mitglieder verteilt, damit das Meeting vorbereitet werden kann.

Die iterative Komponente wird nach dem OpenUP Framework umgesetzt: Plan Iteration -> Manage Iteration -> Assess Results. In der Iterationsplanung werden die fälligen Aufgaben priorisiert. Die einzelnen Aufgaben werden in den zweiwöchig stattfindenden Iterationsmeetings zugeteilt. In der Planung der Iteration ist der Ausgang der vorherigen Iteration maßgebend und dient als Ausgangspunkt für die Darauffolgende. Die aktualisierte Risikobewertung findet hierbei ebenso Berücksichtigung. Gegebenenfalls wird anhand dessen Scope und Projektziel angepasst. Bestandteil des Montagsmeetings ist ebenfalls eine Bewertung und Ergänzung der bekannten Risiken. Bei Veränderung werden diese neu evaluiert. 

In dem Meeting in der darauffolgenden Woche, können die Zuständigkeiten agil an den Bearbeitungsstand angepasst werden. Als Messkriterium des Iterationszyklus-Erfolges dient der prozentuale Anteil absolvierter und durch Teammitglieder überprüfter Aufgaben.

Zur besseren Übersicht werden die zugeteilten Aufgaben in GitHub-Issues eingepflegt und den Teammitgliedern zugewiesen. Die jeweilig verantwortlichen Teammitglieder werden daraufhin per Mail an ihre Aufgabe erinnert. Durch unterschiedliche Labels können die Aufgaben klassifiziert und priorisiert werden. In den Kommentaren unter den jeweiligen Issues können Unteraufgaben oder Arbeitsstände protokolliert werden. 

=== Technical Practices


https://www2.htw-dresden.de/~anke/openup/publish.openup.base/customcategories/technical_practice_list_E425C20F.html?nodeId=cd065eb4[Technical Practices OpenUP]

Im Rahmen des Projektes werden die technischen Praktiken Shared Vision und Use Case Driven Development einbezogen.

Shared Vision bezieht sich im Allgemeinen auf eine einheitliche und durch den Kunden geteilte Ansicht auf die genauen Anforderungen und Erwartungen an das System. Konkret wurde dies durch eine frühzeitige Anfertigung der Vision und deren Besprechung im gesamten Team erreicht. Des Weiteren wurden mehrere Use-Cases angefertigt, um diese den Kunden vorzulegen und so seine Vorstellungen, auf die zu implementierenden Anforderungen, mit der unserer abzugleichen. Damit konnte das Aufgabengebiet in einem Scope eingegrenzt werden und so eine zeiteffektivere und genauere Priorisierung der einzelnen Aufgaben erreicht werden.

Use Case Driven Development bezieht sich allgemein auf eine präzise Dokumentation des zu erreichenden Systemverhaltens, als auch zur Sicherstellung, dass die angefertigte Software testbar ist und einen funktionalen Mehrwert besitzt. Um das zu erreichen haben wir Use-Cases und funktionale als auch nicht funktionale Requirements ausgearbeitet. Anhand des Use-Case-Models können wir im Laufe des Projektes unseren Fortschritt validieren und haben einen Anhaltspunkt für die Architektur. Mit den Requirements wird die Bedienbarkeit und ein tatsächlicher Nutzen der Software sichergestellt. Dies dient als Leitfaden während der Implementierung, so dass eine qualitative Software entsteht und auch die Zufriedenstellung des Kunden gesichert werden kann.


== Meilensteine und Ziele
//Define and describe the high-level objectives for the iterations and define milestones. For example, use the following table to lay out the schedule. If needed you may group the iterations into phases and use a separate table for each phase

[%header, cols="1,3a,2"]
|===

| Iteration
| Primary objectives (risks and use case scenarios)
| Scheduled start or milestone

| I1
|* Rollenzuweisung
* Kick-off Meeting Auftraggeber
* Coach Meeting
* Erarbeitung der Zielstellung
* Zentrale Risikoanalyse

| From 21.11.2022 to 04.12.2022

| I2
|* Ausarbeitung von Vision, Use-Cases, Qualitätsanforderungen
* 2. Meeting Auftraggeber 
* Auswahl des Frameworks
* Erarbeitung eines Projektplans
* Entwurf einer Architektur
* Review bisheriger Ausarbeitungen
* Risiken neu bewerten
| From 05.12.2022 to 18.12.2022

| I3
| <<Iteration Plan 03: {project-name}, Iterationsplan I03>>
| From 19.12.2022 to 09.01.2023

| I4
| <<Iteration Plan 04: {project-name}, Iterationsplan I04>>
| From 09.01.2023 to 23.01.2023

|===


== Deployment
//Outline the strategy for deploying the software (and its updates) into the production environment.
Die serverseitigen Komponenten der Anwendung werden auf einem Server der HTW-Dresden betrieben, im Laufe des 2. Semesters wird diese dann auf einem Server vom Auftraggeber installiert und auch nach Beendigung von dort aus ansprechbar sein. Die Anwendung in Form einer Android-App wird nach Fertigstellung auf einem portablen Speichermedium oder einer Cloud bereitstehen, was zum gegeben Zeitpunkt mit dem Auftraggeber noch besprochen wird. Während der Entwicklung der Anwendung, wird diese, bei Implementation neuer Features, dem Auftraggeber in Form einer ZIP Datei zugänglich gemacht und gegebenenfalls auch von uns installiert.

== Erkenntnisse (Lessons learned)
//List lessons learned from the retrospective, with special emphasis on actions to be taken to improve, for example: the development environment, the process, or team collaboration.


- Die Tools und die genaue Projektmanagementmethode hätten von Anfang an vollständig bekannt sein sollen, da spätere Methodenänderungen sich als schwer etablierbar herausstellten. Zum Beispiel hätte GitHub-Issues vollständig beherrscht werden sollen und ein adäquates Kanbantool genutzt werden müssen (vgl. Taiga). Das fehlende Kanbanboard wurde zwar durch einen Workaround bestehend aus GitHub-Issues mit entsprechenden Labels beseitigt, die Umsetzung war jedoch deutlich umständlicher als es ein konventionelles Kanban wäre.
- Das Essence Navigator Tool wurde nicht von Anfang an verwendet. Dies hat das Problem mit sich gebracht, dass zwar einzelne Aufgaben vergeben werden konnten, auf Managementebene jedoch der allgemeine Überblick gefehlt hat. Da wir uns hier jedoch an den Vorlesungsfolien zum OpenUP orientierten, konnten wir dieses Problem mit Mehraufwand umgehen. 
- Die Use-Cases wurden nicht agil genug entwickelt. So hat die Erstellung der Use-Cases bedeutend länger gedauert als es müsste, da hier nicht agil auf den Arbeitsaufwand eingegangen wurde. Mit einer Anpassung der Human Ressources hätte diesem Problem entgegengewirkt werden können.
- Der Terminfindungsprozess stellte gelegentlich ein Problem dar, da es bei einer Gruppe aus sieben Studierenden häufig zu Überschneidungen individueller Zeitplanungen kommt. Hier kann ein Terminfindungstool Abhilfe schaffen.