= Protokoll: Cycle Meeting KW 49
Leon Lowa <leon.lowa@htw-dresden.de>
v1.0, 05.12.22 18.30 Uhr - 19.30 Uhr
include::../_includes/default-attributes.inc.adoc[]
{localdatetime}



// Platzhalter für weitere Dokumenten-Attribute

== Anwesende
* Carl Ulrich Brinker
* Marcel Axmann
* Manuel Scheer
* Leon Lowa
* Michael Novak
* Jonas Pfeiffer

== Abwesende
* Magnus Andreas Böhne



== Agenda
.	Vorstellung Ausarbeitungen 
.	Meeting Agenda f. 06.12.2022
.	Anstehende Aufgaben verteilen
.	Organisation




=== Vorstellung Ausarbeitungen

Ergebnis:: 

****

Leon, Jonas -> Use-Cases: ::
* 8 Identifiziert und ausgearbeitet
* *Offen*: Use-Case-Diagramm, Verfeinerung der UC nach Rücksprache mit Coach, in Github einpflegen

Manuel, Michael -> Vision: ::
* GPS-Android App verlinkt, fachliche Motivation, Scope ausgearbeitet, Problem-Statement, Stakeholder ausgearbeitet.
* In Github bereits eingepflegt.
* *Offen*: Bedarfe und Hauptfunktion, zusätzliche Produktanforderungen, Produktlösungsüberblick

Marcel -> App von vorheriger Gruppe analysiert: ::
* Vieles in Java programmiert
* Server mit Python
* App sehr simpel gehalten
* Routen können gespeichert werden
* *Wiederverwendbare Funktionen*: eventuell Karte, GPS-tracking mit einbinden

Magnus -> Springboot analysiert: ::
* einfache und schlanke Syntax
* modern
* vereinfachte Maven-Konfiguration
* viele Einstellungen können in Properties-Dateien festgelegt werden (Setup wird erleichtert)
* vieles wird von Haus automatisch Konfiguriert
* sehr flexibel, es sieht unwahrscheinlich aus, dass die Implmentierung aufgrund des Framework sich als schwierig erweist
* man kann es sehr unkompliziert aufsetzen
* hat eine große Community (Fehler können schneller behoben werden)
* der "Kunde" hat es empfohlen 

Das Framework ist für Large- Scale Projekte aufgrund der einfachen Struktur sehr schwierig in der Anwendung. Jedoch ist es ideal für kleine bis mittlere Projekte, da man sich schneller in Springboot einarbeiten kann und die Entwicklung von kleineren Software- Projekten deutlicher weniger Zeit in Anspruch nimmt.
-> Schlussfolgerung: Das Framework wäre geeignet.

****

=== Meeting Agenda für Coachmeeting 06.12.2022

Ergebnis:: 
****
erledigt
****

=== Anstehende Aufgaben verteilen

Ergebnis:: 
****
Leon, Jonas::
Use-Case-Diagramm
Manuel::
Vision weiter ausarbeiten
Michael, Uli::
Usability
Marcel, Magnus::
Reliability, Performance, Supportability


****

=== Organisation

Ergebnis:: 
****
erledigt

****
