= Protokoll: Cycle Meeting KW 52
Carl Ulrich Brinker <carlulrich.brinker@htw-dresden.de>
v1.0, 27.12.22 16.30 Uhr - 17.30
include::../_includes/default-attributes.inc.adoc[]
{localdatetime}



// Platzhalter für weitere Dokumenten-Attribute

== Anwesende
* Carl Ulrich Brinker
* Marcel Axmann
* Manuel Scheer
* Leon Lowa
* Michael Novak
* Jonas Pfeiffer
* Magnus Andreas Böhne



== Agenda
.	Arbeitsstand absprechen
.   Probleme besprechen
.   Neue Aufgaben besprechen



=== Arbeitsstand absprechen

Wireframes -> Uli:: 
****
Verbesserungen: Email weg, stattedessen einfach mittels Token; Routenverwaltung (soll route abspeichern?, beenden, löschen -> nach follow me speichern?)
****

Risikoliste -> Leon:: 
****
Sprache korrigiert, Neugewichtung von Punkten wurden besprochen, neue Risiken identifizieren?, Nr. 5 anders gewichten -> Risiken werden abgeändert
****

Aufgabe Tessystem Framework -> Leon:: 
****
- Leon braucht Hilfe beim Server einrichten
- Rest probehalber eingerichtet
- Entscheidung für Serverarchitektur wurde diskutiert
- -> Todo: Einarbeitung in Serverarchitektur
****

Serverentscheidung -> Marcel, Magnus:: 
****
- wurde noch nicht entschieden
****

Use-Cases -> Jonaes, Manuel, Michael:: 
****
- eine Userstories gemacht
- usecases wurde nicht vereinfacht
- jonas trifft sich mit michael für entscheidung

****

Furps + -> Michael:: 
****
- Fertig
- TODO: Review

****



=== Probleme besprechen

Manuel:: 
****
kleinere Probleme zur Vision wurden besprochen
****

Architecture Notebook -> Marcel:: 
****
kein Forschritt, erfolgt erst nach Architekturmodell
****

Prototyp -> Jonas:: 
****
kein Forschritt, spätestens zum Ende der nächsten Iteration
****

Magnus:: 
****
hat erfolgreich am Springbootcamp teilgenommen
****

=== Anstehende Aufgaben verteilen

Ergebnis:: 
****
- Uli, Michael -> Wireframes
- Jonas,Leon -> Prototyp
- Marcel, Magnus -> Serverentscheidung
- Uli -> Review Furps+
- Marcel -> Architecture Notebook
- Michael -> Einarbeitung Serverarchitektur
- Leon -> Risiken abändern

****

